2025-08-27 23:40:51,757 - matplotlib - DEBUG - matplotlib data path: C:\Users\pablo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\matplotlib\mpl-data
2025-08-27 23:40:51,775 - matplotlib - DEBUG - CONFIGDIR=C:\Users\pablo\.matplotlib
2025-08-27 23:40:51,777 - matplotlib - DEBUG - interactive is False
2025-08-27 23:40:51,778 - matplotlib - DEBUG - platform is win32
2025-08-27 23:40:51,806 - root - INFO - Matplotlib backend configurado correctamente
2025-08-27 23:40:51,861 - root - INFO - CustomTkinter importado correctamente
2025-08-27 23:40:51,901 - root - CRITICAL - No se pudo importar GenealogyApp: cannot import name 'RelacionService' from partially initialized module 'services.relacion_service' (most likely due to a circular import) (c:\Users\pablo\OneDrive\Escritorio\ArbolGenealogico\services\relacion_service.py)
2025-08-27 23:40:51,901 - root - CRITICAL - Verifica la estructura del proyecto:
2025-08-27 23:40:51,902 - root - CRITICAL - Debe tener la siguiente estructura:
2025-08-27 23:40:51,902 - root - CRITICAL - proyecto/
2025-08-27 23:40:52,016 - root - CRITICAL - Error FATAL al importar módulos: cannot import name 'RelacionService' from partially initialized module 'services.relacion_service' (most likely due to a circular import) (c:\Users\pablo\OneDrive\Escritorio\ArbolGenealogico\services\relacion_service.py)
Traceback (most recent call last):
  File "c:\Users\pablo\OneDrive\Escritorio\ArbolGenealogico\main.py", line 35, in <module>
    from gui.app import GenealogyApp
  File "c:\Users\pablo\OneDrive\Escritorio\ArbolGenealogico\gui\app.py", line 14, in <module>
    from services.relacion_service import RelacionService
  File "c:\Users\pablo\OneDrive\Escritorio\ArbolGenealogico\services\relacion_service.py", line 5, in <module>
    from services.simulacion_service import SimulacionService
  File "c:\Users\pablo\OneDrive\Escritorio\ArbolGenealogico\services\simulacion_service.py", line 9, in <module>
    from services.relacion_service import RelacionService
ImportError: cannot import name 'RelacionService' from partially initialized module 'services.relacion_service' (most likely due to a circular import) (c:\Users\pablo\OneDrive\Escritorio\ArbolGenealogico\services\relacion_service.py)
2025-08-28 00:32:56,723 - matplotlib - DEBUG - matplotlib data path: C:\Users\pablo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\matplotlib\mpl-data
2025-08-28 00:32:56,741 - matplotlib - DEBUG - CONFIGDIR=C:\Users\pablo\.matplotlib
2025-08-28 00:32:56,742 - matplotlib - DEBUG - interactive is False
2025-08-28 00:32:56,742 - matplotlib - DEBUG - platform is win32
2025-08-28 00:32:56,768 - root - INFO - Matplotlib backend configurado correctamente
2025-08-28 00:32:56,822 - root - INFO - CustomTkinter importado correctamente
2025-08-28 00:32:56,863 - root - CRITICAL - No se pudo importar GenealogyApp: No module named 'services.utils_service'
2025-08-28 00:32:56,863 - root - CRITICAL - Verifica la estructura del proyecto:
2025-08-28 00:32:56,863 - root - CRITICAL - Debe tener la siguiente estructura:
2025-08-28 00:32:56,864 - root - CRITICAL - proyecto/
2025-08-28 00:32:56,937 - root - CRITICAL - Error FATAL al importar módulos: No module named 'services.utils_service'
Traceback (most recent call last):
  File "c:\Users\pablo\OneDrive\Escritorio\ArbolGenealogico\main.py", line 35, in <module>
    from gui.app import GenealogyApp
  File "c:\Users\pablo\OneDrive\Escritorio\ArbolGenealogico\gui\app.py", line 14, in <module>
    from services.relacion_service import RelacionService
  File "c:\Users\pablo\OneDrive\Escritorio\ArbolGenealogico\services\relacion_service.py", line 5, in <module>
    from services.utils_service import verificar_requisitos_union
ModuleNotFoundError: No module named 'services.utils_service'
2025-08-28 00:33:59,496 - matplotlib - DEBUG - matplotlib data path: C:\Users\pablo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\matplotlib\mpl-data
2025-08-28 00:33:59,511 - matplotlib - DEBUG - CONFIGDIR=C:\Users\pablo\.matplotlib
2025-08-28 00:33:59,512 - matplotlib - DEBUG - interactive is False
2025-08-28 00:33:59,513 - matplotlib - DEBUG - platform is win32
2025-08-28 00:33:59,534 - root - INFO - Matplotlib backend configurado correctamente
2025-08-28 00:33:59,583 - root - INFO - CustomTkinter importado correctamente
2025-08-28 00:33:59,591 - root - CRITICAL - No se pudo importar GenealogyApp: No module named 'services.utils_service'
2025-08-28 00:33:59,591 - root - CRITICAL - Verifica la estructura del proyecto:
2025-08-28 00:33:59,591 - root - CRITICAL - Debe tener la siguiente estructura:
2025-08-28 00:33:59,592 - root - CRITICAL - proyecto/
2025-08-28 00:33:59,663 - root - CRITICAL - Error FATAL al importar módulos: No module named 'services.utils_service'
Traceback (most recent call last):
  File "c:\Users\pablo\OneDrive\Escritorio\ArbolGenealogico\main.py", line 35, in <module>
    from gui.app import GenealogyApp
  File "c:\Users\pablo\OneDrive\Escritorio\ArbolGenealogico\gui\app.py", line 14, in <module>
    from services.relacion_service import RelacionService
  File "c:\Users\pablo\OneDrive\Escritorio\ArbolGenealogico\services\relacion_service.py", line 5, in <module>
    from services.utils_service import verificar_requisitos_union
ModuleNotFoundError: No module named 'services.utils_service'
2025-08-28 00:49:13,413 - matplotlib - DEBUG - matplotlib data path: C:\Users\pablo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\matplotlib\mpl-data
2025-08-28 00:49:13,437 - matplotlib - DEBUG - CONFIGDIR=C:\Users\pablo\.matplotlib
2025-08-28 00:49:13,438 - matplotlib - DEBUG - interactive is False
2025-08-28 00:49:13,439 - matplotlib - DEBUG - platform is win32
2025-08-28 00:49:13,455 - matplotlib - DEBUG - matplotlib data path: C:\Users\pablo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\matplotlib\mpl-data
2025-08-28 00:49:13,463 - root - INFO - Matplotlib backend configurado correctamente
2025-08-28 00:49:13,474 - matplotlib - DEBUG - CONFIGDIR=C:\Users\pablo\.matplotlib
2025-08-28 00:49:13,476 - matplotlib - DEBUG - interactive is False
2025-08-28 00:49:13,477 - matplotlib - DEBUG - platform is win32
2025-08-28 00:49:13,503 - root - INFO - Matplotlib backend configurado correctamente
2025-08-28 00:49:13,519 - root - INFO - CustomTkinter importado correctamente
2025-08-28 00:49:13,553 - root - INFO - CustomTkinter importado correctamente
2025-08-28 00:49:14,009 - matplotlib - DEBUG - CACHEDIR=C:\Users\pablo\.matplotlib
2025-08-28 00:49:14,009 - matplotlib - DEBUG - CACHEDIR=C:\Users\pablo\.matplotlib
2025-08-28 00:49:14,012 - matplotlib.font_manager - DEBUG - Using fontManager instance from C:\Users\pablo\.matplotlib\fontlist-v390.json
2025-08-28 00:49:14,012 - matplotlib.font_manager - DEBUG - Using fontManager instance from C:\Users\pablo\.matplotlib\fontlist-v390.json
2025-08-28 00:49:14,415 - root - INFO - Módulo gui.app importado correctamente
2025-08-28 00:49:14,415 - root - INFO - Módulo gui.app importado correctamente
2025-08-28 00:49:14,416 - root - INFO - Configuración de CustomTkinter establecida
2025-08-28 00:49:14,416 - root - INFO - Configuración de CustomTkinter establecida
2025-08-28 00:49:14,588 - root - INFO - Ventana principal creada
2025-08-28 00:49:14,597 - root - INFO - Ventana principal creada
2025-08-28 00:49:15,518 - root - ERROR - Error inesperado al inicializar GenealogyApp
2025-08-28 00:49:15,519 - root - ERROR - Detalles: No module named 'gui.graph_visualizer'
2025-08-28 00:49:15,521 - root - ERROR - Error inesperado al inicializar GenealogyApp
2025-08-28 00:49:15,521 - root - ERROR - Detalles: No module named 'gui.graph_visualizer'
2025-08-28 00:57:21,072 - matplotlib - DEBUG - matplotlib data path: C:\Users\pablo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\matplotlib\mpl-data
2025-08-28 00:57:21,095 - matplotlib - DEBUG - CONFIGDIR=C:\Users\pablo\.matplotlib
2025-08-28 00:57:21,098 - matplotlib - DEBUG - interactive is False
2025-08-28 00:57:21,099 - matplotlib - DEBUG - platform is win32
2025-08-28 00:57:21,175 - root - INFO - Matplotlib backend configurado correctamente
2025-08-28 00:57:21,259 - root - INFO - CustomTkinter importado correctamente
2025-08-28 00:57:21,443 - matplotlib - DEBUG - CACHEDIR=C:\Users\pablo\.matplotlib
2025-08-28 00:57:21,446 - matplotlib.font_manager - DEBUG - Using fontManager instance from C:\Users\pablo\.matplotlib\fontlist-v390.json
2025-08-28 00:57:21,689 - root - INFO - Módulo gui.app importado correctamente
2025-08-28 00:57:21,690 - root - INFO - Configuración de CustomTkinter establecida
2025-08-28 00:57:21,806 - root - INFO - Ventana principal creada
2025-08-28 00:57:22,349 - root - INFO - GenealogyApp inicializada correctamente
2025-08-28 00:57:22,349 - root - INFO - Iniciando bucle principal de la aplicación...
2025-08-28 01:10:11,757 - root - ERROR - Error en simulación: 'FamilyGraphVisualizer' object has no attribute 'draw_tree'
Traceback (most recent call last):
  File "c:\Users\pablo\OneDrive\Escritorio\ArbolGenealogico\gui\simulation_panel.py", line 141, in run_simulation
    self.draw_tree()
    ~~~~~~~~~~~~~~^^
  File "c:\Users\pablo\OneDrive\Escritorio\ArbolGenealogico\gui\simulation_panel.py", line 227, in draw_tree
    visualizer.draw_tree(self.simulated_family, self.tree_canvas)
    ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'FamilyGraphVisualizer' object has no attribute 'draw_tree'
2025-08-28 01:10:21,713 - root - ERROR - Error en simulación: No module named 'services.utils_service'
Traceback (most recent call last):
  File "c:\Users\pablo\OneDrive\Escritorio\ArbolGenealogico\gui\simulation_panel.py", line 125, in run_simulation
    eventos = SimulacionService.ejecutar_ciclo_completo(
        self.simulated_family,
        self.config
    )
  File "c:\Users\pablo\OneDrive\Escritorio\ArbolGenealogico\services\simulacion_service.py", line 504, in ejecutar_ciclo_completo
    romance_events = SimulacionService.procesar_busqueda_parejas(family, config)
  File "c:\Users\pablo\OneDrive\Escritorio\ArbolGenealogico\services\simulacion_service.py", line 779, in procesar_busqueda_parejas
    success, message = RelacionService.registrar_pareja(family, person.cedula, partner.cedula)
                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\pablo\OneDrive\Escritorio\ArbolGenealogico\services\relacion_service.py", line 101, in registrar_pareja
    from services.utils_service import verificar_requisitos_union
ModuleNotFoundError: No module named 'services.utils_service'
2025-08-28 01:10:21,896 - root - ERROR - Error en simulación: 'FamilyGraphVisualizer' object has no attribute 'draw_tree'
Traceback (most recent call last):
  File "c:\Users\pablo\OneDrive\Escritorio\ArbolGenealogico\gui\simulation_panel.py", line 141, in run_simulation
    self.draw_tree()
    ~~~~~~~~~~~~~~^^
  File "c:\Users\pablo\OneDrive\Escritorio\ArbolGenealogico\gui\simulation_panel.py", line 227, in draw_tree
    visualizer.draw_tree(self.simulated_family, self.tree_canvas)
    ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'FamilyGraphVisualizer' object has no attribute 'draw_tree'
2025-08-28 01:16:11,813 - root - ERROR - Error en simulación: 'FamilyGraphVisualizer' object has no attribute 'draw_tree'
Traceback (most recent call last):
  File "c:\Users\pablo\OneDrive\Escritorio\ArbolGenealogico\gui\simulation_panel.py", line 141, in run_simulation
    self.draw_tree()
    ~~~~~~~~~~~~~~^^
  File "c:\Users\pablo\OneDrive\Escritorio\ArbolGenealogico\gui\simulation_panel.py", line 227, in draw_tree
    visualizer.draw_tree(self.simulated_family, self.tree_canvas)
    ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'FamilyGraphVisualizer' object has no attribute 'draw_tree'
2025-08-28 01:16:21,893 - root - ERROR - Error en simulación: 'FamilyGraphVisualizer' object has no attribute 'draw_tree'
Traceback (most recent call last):
  File "c:\Users\pablo\OneDrive\Escritorio\ArbolGenealogico\gui\simulation_panel.py", line 141, in run_simulation
    self.draw_tree()
    ~~~~~~~~~~~~~~^^
  File "c:\Users\pablo\OneDrive\Escritorio\ArbolGenealogico\gui\simulation_panel.py", line 227, in draw_tree
    visualizer.draw_tree(self.simulated_family, self.tree_canvas)
    ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'FamilyGraphVisualizer' object has no attribute 'draw_tree'
2025-08-28 01:16:31,977 - root - ERROR - Error en simulación: 'FamilyGraphVisualizer' object has no attribute 'draw_tree'
Traceback (most recent call last):
  File "c:\Users\pablo\OneDrive\Escritorio\ArbolGenealogico\gui\simulation_panel.py", line 141, in run_simulation
    self.draw_tree()
    ~~~~~~~~~~~~~~^^
  File "c:\Users\pablo\OneDrive\Escritorio\ArbolGenealogico\gui\simulation_panel.py", line 227, in draw_tree
    visualizer.draw_tree(self.simulated_family, self.tree_canvas)
    ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'FamilyGraphVisualizer' object has no attribute 'draw_tree'
2025-08-28 01:16:42,062 - root - ERROR - Error en simulación: 'FamilyGraphVisualizer' object has no attribute 'draw_tree'
Traceback (most recent call last):
  File "c:\Users\pablo\OneDrive\Escritorio\ArbolGenealogico\gui\simulation_panel.py", line 141, in run_simulation
    self.draw_tree()
    ~~~~~~~~~~~~~~^^
  File "c:\Users\pablo\OneDrive\Escritorio\ArbolGenealogico\gui\simulation_panel.py", line 227, in draw_tree
    visualizer.draw_tree(self.simulated_family, self.tree_canvas)
    ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'FamilyGraphVisualizer' object has no attribute 'draw_tree'
2025-08-28 01:16:52,134 - root - ERROR - Error en simulación: 'FamilyGraphVisualizer' object has no attribute 'draw_tree'
Traceback (most recent call last):
  File "c:\Users\pablo\OneDrive\Escritorio\ArbolGenealogico\gui\simulation_panel.py", line 141, in run_simulation
    self.draw_tree()
    ~~~~~~~~~~~~~~^^
  File "c:\Users\pablo\OneDrive\Escritorio\ArbolGenealogico\gui\simulation_panel.py", line 227, in draw_tree
    visualizer.draw_tree(self.simulated_family, self.tree_canvas)
    ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'FamilyGraphVisualizer' object has no attribute 'draw_tree'
2025-08-28 01:17:02,235 - root - ERROR - Error en simulación: 'FamilyGraphVisualizer' object has no attribute 'draw_tree'
Traceback (most recent call last):
  File "c:\Users\pablo\OneDrive\Escritorio\ArbolGenealogico\gui\simulation_panel.py", line 141, in run_simulation
    self.draw_tree()
    ~~~~~~~~~~~~~~^^
  File "c:\Users\pablo\OneDrive\Escritorio\ArbolGenealogico\gui\simulation_panel.py", line 227, in draw_tree
    visualizer.draw_tree(self.simulated_family, self.tree_canvas)
    ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'FamilyGraphVisualizer' object has no attribute 'draw_tree'
2025-08-28 01:17:12,316 - root - ERROR - Error en simulación: 'FamilyGraphVisualizer' object has no attribute 'draw_tree'
Traceback (most recent call last):
  File "c:\Users\pablo\OneDrive\Escritorio\ArbolGenealogico\gui\simulation_panel.py", line 141, in run_simulation
    self.draw_tree()
    ~~~~~~~~~~~~~~^^
  File "c:\Users\pablo\OneDrive\Escritorio\ArbolGenealogico\gui\simulation_panel.py", line 227, in draw_tree
    visualizer.draw_tree(self.simulated_family, self.tree_canvas)
    ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'FamilyGraphVisualizer' object has no attribute 'draw_tree'
2025-08-28 01:17:22,411 - root - ERROR - Error en simulación: 'FamilyGraphVisualizer' object has no attribute 'draw_tree'
Traceback (most recent call last):
  File "c:\Users\pablo\OneDrive\Escritorio\ArbolGenealogico\gui\simulation_panel.py", line 141, in run_simulation
    self.draw_tree()
    ~~~~~~~~~~~~~~^^
  File "c:\Users\pablo\OneDrive\Escritorio\ArbolGenealogico\gui\simulation_panel.py", line 227, in draw_tree
    visualizer.draw_tree(self.simulated_family, self.tree_canvas)
    ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'FamilyGraphVisualizer' object has no attribute 'draw_tree'
2025-08-28 01:17:32,462 - root - ERROR - Error en simulación: No module named 'services.utils_service'
Traceback (most recent call last):
  File "c:\Users\pablo\OneDrive\Escritorio\ArbolGenealogico\gui\simulation_panel.py", line 125, in run_simulation
    eventos = SimulacionService.ejecutar_ciclo_completo(
        self.simulated_family,
        self.config
    )
  File "c:\Users\pablo\OneDrive\Escritorio\ArbolGenealogico\services\simulacion_service.py", line 504, in ejecutar_ciclo_completo
    romance_events = SimulacionService.procesar_busqueda_parejas(family, config)
  File "c:\Users\pablo\OneDrive\Escritorio\ArbolGenealogico\services\simulacion_service.py", line 779, in procesar_busqueda_parejas
    success, message = RelacionService.registrar_pareja(family, person.cedula, partner.cedula)
                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\pablo\OneDrive\Escritorio\ArbolGenealogico\services\relacion_service.py", line 101, in registrar_pareja
    from services.utils_service import verificar_requisitos_union
ModuleNotFoundError: No module named 'services.utils_service'
2025-08-28 01:17:32,601 - root - ERROR - Error en simulación: 'FamilyGraphVisualizer' object has no attribute 'draw_tree'
Traceback (most recent call last):
  File "c:\Users\pablo\OneDrive\Escritorio\ArbolGenealogico\gui\simulation_panel.py", line 141, in run_simulation
    self.draw_tree()
    ~~~~~~~~~~~~~~^^
  File "c:\Users\pablo\OneDrive\Escritorio\ArbolGenealogico\gui\simulation_panel.py", line 227, in draw_tree
    visualizer.draw_tree(self.simulated_family, self.tree_canvas)
    ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'FamilyGraphVisualizer' object has no attribute 'draw_tree'
2025-08-28 01:17:42,677 - root - ERROR - Error en simulación: 'FamilyGraphVisualizer' object has no attribute 'draw_tree'
Traceback (most recent call last):
  File "c:\Users\pablo\OneDrive\Escritorio\ArbolGenealogico\gui\simulation_panel.py", line 141, in run_simulation
    self.draw_tree()
    ~~~~~~~~~~~~~~^^
  File "c:\Users\pablo\OneDrive\Escritorio\ArbolGenealogico\gui\simulation_panel.py", line 227, in draw_tree
    visualizer.draw_tree(self.simulated_family, self.tree_canvas)
    ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'FamilyGraphVisualizer' object has no attribute 'draw_tree'
2025-08-28 01:17:52,775 - root - ERROR - Error en simulación: 'FamilyGraphVisualizer' object has no attribute 'draw_tree'
Traceback (most recent call last):
  File "c:\Users\pablo\OneDrive\Escritorio\ArbolGenealogico\gui\simulation_panel.py", line 141, in run_simulation
    self.draw_tree()
    ~~~~~~~~~~~~~~^^
  File "c:\Users\pablo\OneDrive\Escritorio\ArbolGenealogico\gui\simulation_panel.py", line 227, in draw_tree
    visualizer.draw_tree(self.simulated_family, self.tree_canvas)
    ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'FamilyGraphVisualizer' object has no attribute 'draw_tree'
2025-08-28 01:18:02,864 - root - ERROR - Error en simulación: 'FamilyGraphVisualizer' object has no attribute 'draw_tree'
Traceback (most recent call last):
  File "c:\Users\pablo\OneDrive\Escritorio\ArbolGenealogico\gui\simulation_panel.py", line 141, in run_simulation
    self.draw_tree()
    ~~~~~~~~~~~~~~^^
  File "c:\Users\pablo\OneDrive\Escritorio\ArbolGenealogico\gui\simulation_panel.py", line 227, in draw_tree
    visualizer.draw_tree(self.simulated_family, self.tree_canvas)
    ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'FamilyGraphVisualizer' object has no attribute 'draw_tree'
2025-08-28 01:18:12,952 - root - ERROR - Error en simulación: 'FamilyGraphVisualizer' object has no attribute 'draw_tree'
Traceback (most recent call last):
  File "c:\Users\pablo\OneDrive\Escritorio\ArbolGenealogico\gui\simulation_panel.py", line 141, in run_simulation
    self.draw_tree()
    ~~~~~~~~~~~~~~^^
  File "c:\Users\pablo\OneDrive\Escritorio\ArbolGenealogico\gui\simulation_panel.py", line 227, in draw_tree
    visualizer.draw_tree(self.simulated_family, self.tree_canvas)
    ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'FamilyGraphVisualizer' object has no attribute 'draw_tree'
2025-08-28 01:18:23,039 - root - ERROR - Error en simulación: 'FamilyGraphVisualizer' object has no attribute 'draw_tree'
Traceback (most recent call last):
  File "c:\Users\pablo\OneDrive\Escritorio\ArbolGenealogico\gui\simulation_panel.py", line 141, in run_simulation
    self.draw_tree()
    ~~~~~~~~~~~~~~^^
  File "c:\Users\pablo\OneDrive\Escritorio\ArbolGenealogico\gui\simulation_panel.py", line 227, in draw_tree
    visualizer.draw_tree(self.simulated_family, self.tree_canvas)
    ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'FamilyGraphVisualizer' object has no attribute 'draw_tree'
2025-08-28 01:18:33,092 - root - ERROR - Error en simulación: No module named 'services.utils_service'
Traceback (most recent call last):
  File "c:\Users\pablo\OneDrive\Escritorio\ArbolGenealogico\gui\simulation_panel.py", line 125, in run_simulation
    eventos = SimulacionService.ejecutar_ciclo_completo(
        self.simulated_family,
        self.config
    )
  File "c:\Users\pablo\OneDrive\Escritorio\ArbolGenealogico\services\simulacion_service.py", line 504, in ejecutar_ciclo_completo
    romance_events = SimulacionService.procesar_busqueda_parejas(family, config)
  File "c:\Users\pablo\OneDrive\Escritorio\ArbolGenealogico\services\simulacion_service.py", line 779, in procesar_busqueda_parejas
    success, message = RelacionService.registrar_pareja(family, person.cedula, partner.cedula)
                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\pablo\OneDrive\Escritorio\ArbolGenealogico\services\relacion_service.py", line 101, in registrar_pareja
    from services.utils_service import verificar_requisitos_union
ModuleNotFoundError: No module named 'services.utils_service'
2025-08-28 01:18:33,236 - root - ERROR - Error en simulación: 'FamilyGraphVisualizer' object has no attribute 'draw_tree'
Traceback (most recent call last):
  File "c:\Users\pablo\OneDrive\Escritorio\ArbolGenealogico\gui\simulation_panel.py", line 141, in run_simulation
    self.draw_tree()
    ~~~~~~~~~~~~~~^^
  File "c:\Users\pablo\OneDrive\Escritorio\ArbolGenealogico\gui\simulation_panel.py", line 227, in draw_tree
    visualizer.draw_tree(self.simulated_family, self.tree_canvas)
    ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'FamilyGraphVisualizer' object has no attribute 'draw_tree'
2025-08-28 01:18:43,321 - root - ERROR - Error en simulación: 'FamilyGraphVisualizer' object has no attribute 'draw_tree'
Traceback (most recent call last):
  File "c:\Users\pablo\OneDrive\Escritorio\ArbolGenealogico\gui\simulation_panel.py", line 141, in run_simulation
    self.draw_tree()
    ~~~~~~~~~~~~~~^^
  File "c:\Users\pablo\OneDrive\Escritorio\ArbolGenealogico\gui\simulation_panel.py", line 227, in draw_tree
    visualizer.draw_tree(self.simulated_family, self.tree_canvas)
    ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'FamilyGraphVisualizer' object has no attribute 'draw_tree'
2025-08-28 01:18:53,414 - root - ERROR - Error en simulación: 'FamilyGraphVisualizer' object has no attribute 'draw_tree'
Traceback (most recent call last):
  File "c:\Users\pablo\OneDrive\Escritorio\ArbolGenealogico\gui\simulation_panel.py", line 141, in run_simulation
    self.draw_tree()
    ~~~~~~~~~~~~~~^^
  File "c:\Users\pablo\OneDrive\Escritorio\ArbolGenealogico\gui\simulation_panel.py", line 227, in draw_tree
    visualizer.draw_tree(self.simulated_family, self.tree_canvas)
    ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'FamilyGraphVisualizer' object has no attribute 'draw_tree'
2025-08-28 01:19:03,464 - root - ERROR - Error en simulación: No module named 'services.utils_service'
Traceback (most recent call last):
  File "c:\Users\pablo\OneDrive\Escritorio\ArbolGenealogico\gui\simulation_panel.py", line 125, in run_simulation
    eventos = SimulacionService.ejecutar_ciclo_completo(
        self.simulated_family,
        self.config
    )
  File "c:\Users\pablo\OneDrive\Escritorio\ArbolGenealogico\services\simulacion_service.py", line 504, in ejecutar_ciclo_completo
    romance_events = SimulacionService.procesar_busqueda_parejas(family, config)
  File "c:\Users\pablo\OneDrive\Escritorio\ArbolGenealogico\services\simulacion_service.py", line 779, in procesar_busqueda_parejas
    success, message = RelacionService.registrar_pareja(family, person.cedula, partner.cedula)
                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\pablo\OneDrive\Escritorio\ArbolGenealogico\services\relacion_service.py", line 101, in registrar_pareja
    from services.utils_service import verificar_requisitos_union
ModuleNotFoundError: No module named 'services.utils_service'
2025-08-28 01:19:03,610 - root - ERROR - Error en simulación: 'FamilyGraphVisualizer' object has no attribute 'draw_tree'
Traceback (most recent call last):
  File "c:\Users\pablo\OneDrive\Escritorio\ArbolGenealogico\gui\simulation_panel.py", line 141, in run_simulation
    self.draw_tree()
    ~~~~~~~~~~~~~~^^
  File "c:\Users\pablo\OneDrive\Escritorio\ArbolGenealogico\gui\simulation_panel.py", line 227, in draw_tree
    visualizer.draw_tree(self.simulated_family, self.tree_canvas)
    ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'FamilyGraphVisualizer' object has no attribute 'draw_tree'
2025-08-28 01:19:13,659 - root - ERROR - Error en simulación: No module named 'services.utils_service'
Traceback (most recent call last):
  File "c:\Users\pablo\OneDrive\Escritorio\ArbolGenealogico\gui\simulation_panel.py", line 125, in run_simulation
    eventos = SimulacionService.ejecutar_ciclo_completo(
        self.simulated_family,
        self.config
    )
  File "c:\Users\pablo\OneDrive\Escritorio\ArbolGenealogico\services\simulacion_service.py", line 504, in ejecutar_ciclo_completo
    romance_events = SimulacionService.procesar_busqueda_parejas(family, config)
  File "c:\Users\pablo\OneDrive\Escritorio\ArbolGenealogico\services\simulacion_service.py", line 779, in procesar_busqueda_parejas
    success, message = RelacionService.registrar_pareja(family, person.cedula, partner.cedula)
                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\pablo\OneDrive\Escritorio\ArbolGenealogico\services\relacion_service.py", line 101, in registrar_pareja
    from services.utils_service import verificar_requisitos_union
ModuleNotFoundError: No module named 'services.utils_service'
2025-08-28 01:19:13,803 - root - ERROR - Error en simulación: 'FamilyGraphVisualizer' object has no attribute 'draw_tree'
Traceback (most recent call last):
  File "c:\Users\pablo\OneDrive\Escritorio\ArbolGenealogico\gui\simulation_panel.py", line 141, in run_simulation
    self.draw_tree()
    ~~~~~~~~~~~~~~^^
  File "c:\Users\pablo\OneDrive\Escritorio\ArbolGenealogico\gui\simulation_panel.py", line 227, in draw_tree
    visualizer.draw_tree(self.simulated_family, self.tree_canvas)
    ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'FamilyGraphVisualizer' object has no attribute 'draw_tree'
2025-08-28 01:19:23,891 - root - ERROR - Error en simulación: 'FamilyGraphVisualizer' object has no attribute 'draw_tree'
Traceback (most recent call last):
  File "c:\Users\pablo\OneDrive\Escritorio\ArbolGenealogico\gui\simulation_panel.py", line 141, in run_simulation
    self.draw_tree()
    ~~~~~~~~~~~~~~^^
  File "c:\Users\pablo\OneDrive\Escritorio\ArbolGenealogico\gui\simulation_panel.py", line 227, in draw_tree
    visualizer.draw_tree(self.simulated_family, self.tree_canvas)
    ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'FamilyGraphVisualizer' object has no attribute 'draw_tree'
2025-08-28 01:19:33,970 - root - ERROR - Error en simulación: 'FamilyGraphVisualizer' object has no attribute 'draw_tree'
Traceback (most recent call last):
  File "c:\Users\pablo\OneDrive\Escritorio\ArbolGenealogico\gui\simulation_panel.py", line 141, in run_simulation
    self.draw_tree()
    ~~~~~~~~~~~~~~^^
  File "c:\Users\pablo\OneDrive\Escritorio\ArbolGenealogico\gui\simulation_panel.py", line 227, in draw_tree
    visualizer.draw_tree(self.simulated_family, self.tree_canvas)
    ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'FamilyGraphVisualizer' object has no attribute 'draw_tree'
2025-08-28 01:19:44,060 - root - ERROR - Error en simulación: 'FamilyGraphVisualizer' object has no attribute 'draw_tree'
Traceback (most recent call last):
  File "c:\Users\pablo\OneDrive\Escritorio\ArbolGenealogico\gui\simulation_panel.py", line 141, in run_simulation
    self.draw_tree()
    ~~~~~~~~~~~~~~^^
  File "c:\Users\pablo\OneDrive\Escritorio\ArbolGenealogico\gui\simulation_panel.py", line 227, in draw_tree
    visualizer.draw_tree(self.simulated_family, self.tree_canvas)
    ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'FamilyGraphVisualizer' object has no attribute 'draw_tree'
2025-08-28 01:19:54,153 - root - ERROR - Error en simulación: 'FamilyGraphVisualizer' object has no attribute 'draw_tree'
Traceback (most recent call last):
  File "c:\Users\pablo\OneDrive\Escritorio\ArbolGenealogico\gui\simulation_panel.py", line 141, in run_simulation
    self.draw_tree()
    ~~~~~~~~~~~~~~^^
  File "c:\Users\pablo\OneDrive\Escritorio\ArbolGenealogico\gui\simulation_panel.py", line 227, in draw_tree
    visualizer.draw_tree(self.simulated_family, self.tree_canvas)
    ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'FamilyGraphVisualizer' object has no attribute 'draw_tree'
2025-08-28 01:20:04,236 - root - ERROR - Error en simulación: 'FamilyGraphVisualizer' object has no attribute 'draw_tree'
Traceback (most recent call last):
  File "c:\Users\pablo\OneDrive\Escritorio\ArbolGenealogico\gui\simulation_panel.py", line 141, in run_simulation
    self.draw_tree()
    ~~~~~~~~~~~~~~^^
  File "c:\Users\pablo\OneDrive\Escritorio\ArbolGenealogico\gui\simulation_panel.py", line 227, in draw_tree
    visualizer.draw_tree(self.simulated_family, self.tree_canvas)
    ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'FamilyGraphVisualizer' object has no attribute 'draw_tree'
2025-08-28 01:20:14,316 - root - ERROR - Error en simulación: 'FamilyGraphVisualizer' object has no attribute 'draw_tree'
Traceback (most recent call last):
  File "c:\Users\pablo\OneDrive\Escritorio\ArbolGenealogico\gui\simulation_panel.py", line 141, in run_simulation
    self.draw_tree()
    ~~~~~~~~~~~~~~^^
  File "c:\Users\pablo\OneDrive\Escritorio\ArbolGenealogico\gui\simulation_panel.py", line 227, in draw_tree
    visualizer.draw_tree(self.simulated_family, self.tree_canvas)
    ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'FamilyGraphVisualizer' object has no attribute 'draw_tree'
2025-08-28 01:20:24,394 - root - ERROR - Error en simulación: 'FamilyGraphVisualizer' object has no attribute 'draw_tree'
Traceback (most recent call last):
  File "c:\Users\pablo\OneDrive\Escritorio\ArbolGenealogico\gui\simulation_panel.py", line 141, in run_simulation
    self.draw_tree()
    ~~~~~~~~~~~~~~^^
  File "c:\Users\pablo\OneDrive\Escritorio\ArbolGenealogico\gui\simulation_panel.py", line 227, in draw_tree
    visualizer.draw_tree(self.simulated_family, self.tree_canvas)
    ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'FamilyGraphVisualizer' object has no attribute 'draw_tree'
2025-08-28 01:20:34,460 - root - ERROR - Error en simulación: 'FamilyGraphVisualizer' object has no attribute 'draw_tree'
Traceback (most recent call last):
  File "c:\Users\pablo\OneDrive\Escritorio\ArbolGenealogico\gui\simulation_panel.py", line 141, in run_simulation
    self.draw_tree()
    ~~~~~~~~~~~~~~^^
  File "c:\Users\pablo\OneDrive\Escritorio\ArbolGenealogico\gui\simulation_panel.py", line 227, in draw_tree
    visualizer.draw_tree(self.simulated_family, self.tree_canvas)
    ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'FamilyGraphVisualizer' object has no attribute 'draw_tree'
2025-08-28 01:20:44,534 - root - ERROR - Error en simulación: 'FamilyGraphVisualizer' object has no attribute 'draw_tree'
Traceback (most recent call last):
  File "c:\Users\pablo\OneDrive\Escritorio\ArbolGenealogico\gui\simulation_panel.py", line 141, in run_simulation
    self.draw_tree()
    ~~~~~~~~~~~~~~^^
  File "c:\Users\pablo\OneDrive\Escritorio\ArbolGenealogico\gui\simulation_panel.py", line 227, in draw_tree
    visualizer.draw_tree(self.simulated_family, self.tree_canvas)
    ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'FamilyGraphVisualizer' object has no attribute 'draw_tree'
2025-08-28 01:20:54,608 - root - ERROR - Error en simulación: 'FamilyGraphVisualizer' object has no attribute 'draw_tree'
Traceback (most recent call last):
  File "c:\Users\pablo\OneDrive\Escritorio\ArbolGenealogico\gui\simulation_panel.py", line 141, in run_simulation
    self.draw_tree()
    ~~~~~~~~~~~~~~^^
  File "c:\Users\pablo\OneDrive\Escritorio\ArbolGenealogico\gui\simulation_panel.py", line 227, in draw_tree
    visualizer.draw_tree(self.simulated_family, self.tree_canvas)
    ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'FamilyGraphVisualizer' object has no attribute 'draw_tree'
2025-08-28 01:21:04,676 - root - ERROR - Error en simulación: 'FamilyGraphVisualizer' object has no attribute 'draw_tree'
Traceback (most recent call last):
  File "c:\Users\pablo\OneDrive\Escritorio\ArbolGenealogico\gui\simulation_panel.py", line 141, in run_simulation
    self.draw_tree()
    ~~~~~~~~~~~~~~^^
  File "c:\Users\pablo\OneDrive\Escritorio\ArbolGenealogico\gui\simulation_panel.py", line 227, in draw_tree
    visualizer.draw_tree(self.simulated_family, self.tree_canvas)
    ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'FamilyGraphVisualizer' object has no attribute 'draw_tree'
2025-08-28 01:21:14,760 - root - ERROR - Error en simulación: 'FamilyGraphVisualizer' object has no attribute 'draw_tree'
Traceback (most recent call last):
  File "c:\Users\pablo\OneDrive\Escritorio\ArbolGenealogico\gui\simulation_panel.py", line 141, in run_simulation
    self.draw_tree()
    ~~~~~~~~~~~~~~^^
  File "c:\Users\pablo\OneDrive\Escritorio\ArbolGenealogico\gui\simulation_panel.py", line 227, in draw_tree
    visualizer.draw_tree(self.simulated_family, self.tree_canvas)
    ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'FamilyGraphVisualizer' object has no attribute 'draw_tree'
2025-08-28 01:21:24,839 - root - ERROR - Error en simulación: 'FamilyGraphVisualizer' object has no attribute 'draw_tree'
Traceback (most recent call last):
  File "c:\Users\pablo\OneDrive\Escritorio\ArbolGenealogico\gui\simulation_panel.py", line 141, in run_simulation
    self.draw_tree()
    ~~~~~~~~~~~~~~^^
  File "c:\Users\pablo\OneDrive\Escritorio\ArbolGenealogico\gui\simulation_panel.py", line 227, in draw_tree
    visualizer.draw_tree(self.simulated_family, self.tree_canvas)
    ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'FamilyGraphVisualizer' object has no attribute 'draw_tree'
2025-08-28 01:21:34,909 - root - ERROR - Error en simulación: 'FamilyGraphVisualizer' object has no attribute 'draw_tree'
Traceback (most recent call last):
  File "c:\Users\pablo\OneDrive\Escritorio\ArbolGenealogico\gui\simulation_panel.py", line 141, in run_simulation
    self.draw_tree()
    ~~~~~~~~~~~~~~^^
  File "c:\Users\pablo\OneDrive\Escritorio\ArbolGenealogico\gui\simulation_panel.py", line 227, in draw_tree
    visualizer.draw_tree(self.simulated_family, self.tree_canvas)
    ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'FamilyGraphVisualizer' object has no attribute 'draw_tree'
2025-08-28 01:21:44,979 - root - ERROR - Error en simulación: 'FamilyGraphVisualizer' object has no attribute 'draw_tree'
Traceback (most recent call last):
  File "c:\Users\pablo\OneDrive\Escritorio\ArbolGenealogico\gui\simulation_panel.py", line 141, in run_simulation
    self.draw_tree()
    ~~~~~~~~~~~~~~^^
  File "c:\Users\pablo\OneDrive\Escritorio\ArbolGenealogico\gui\simulation_panel.py", line 227, in draw_tree
    visualizer.draw_tree(self.simulated_family, self.tree_canvas)
    ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'FamilyGraphVisualizer' object has no attribute 'draw_tree'
2025-08-28 01:21:55,046 - root - ERROR - Error en simulación: 'FamilyGraphVisualizer' object has no attribute 'draw_tree'
Traceback (most recent call last):
  File "c:\Users\pablo\OneDrive\Escritorio\ArbolGenealogico\gui\simulation_panel.py", line 141, in run_simulation
    self.draw_tree()
    ~~~~~~~~~~~~~~^^
  File "c:\Users\pablo\OneDrive\Escritorio\ArbolGenealogico\gui\simulation_panel.py", line 227, in draw_tree
    visualizer.draw_tree(self.simulated_family, self.tree_canvas)
    ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'FamilyGraphVisualizer' object has no attribute 'draw_tree'
2025-08-28 01:22:05,105 - root - ERROR - Error en simulación: 'FamilyGraphVisualizer' object has no attribute 'draw_tree'
Traceback (most recent call last):
  File "c:\Users\pablo\OneDrive\Escritorio\ArbolGenealogico\gui\simulation_panel.py", line 141, in run_simulation
    self.draw_tree()
    ~~~~~~~~~~~~~~^^
  File "c:\Users\pablo\OneDrive\Escritorio\ArbolGenealogico\gui\simulation_panel.py", line 227, in draw_tree
    visualizer.draw_tree(self.simulated_family, self.tree_canvas)
    ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'FamilyGraphVisualizer' object has no attribute 'draw_tree'
2025-08-28 01:22:15,171 - root - ERROR - Error en simulación: 'FamilyGraphVisualizer' object has no attribute 'draw_tree'
Traceback (most recent call last):
  File "c:\Users\pablo\OneDrive\Escritorio\ArbolGenealogico\gui\simulation_panel.py", line 141, in run_simulation
    self.draw_tree()
    ~~~~~~~~~~~~~~^^
  File "c:\Users\pablo\OneDrive\Escritorio\ArbolGenealogico\gui\simulation_panel.py", line 227, in draw_tree
    visualizer.draw_tree(self.simulated_family, self.tree_canvas)
    ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'FamilyGraphVisualizer' object has no attribute 'draw_tree'
2025-08-28 01:22:25,236 - root - ERROR - Error en simulación: 'FamilyGraphVisualizer' object has no attribute 'draw_tree'
Traceback (most recent call last):
  File "c:\Users\pablo\OneDrive\Escritorio\ArbolGenealogico\gui\simulation_panel.py", line 141, in run_simulation
    self.draw_tree()
    ~~~~~~~~~~~~~~^^
  File "c:\Users\pablo\OneDrive\Escritorio\ArbolGenealogico\gui\simulation_panel.py", line 227, in draw_tree
    visualizer.draw_tree(self.simulated_family, self.tree_canvas)
    ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'FamilyGraphVisualizer' object has no attribute 'draw_tree'
2025-08-28 01:22:35,303 - root - ERROR - Error en simulación: 'FamilyGraphVisualizer' object has no attribute 'draw_tree'
Traceback (most recent call last):
  File "c:\Users\pablo\OneDrive\Escritorio\ArbolGenealogico\gui\simulation_panel.py", line 141, in run_simulation
    self.draw_tree()
    ~~~~~~~~~~~~~~^^
  File "c:\Users\pablo\OneDrive\Escritorio\ArbolGenealogico\gui\simulation_panel.py", line 227, in draw_tree
    visualizer.draw_tree(self.simulated_family, self.tree_canvas)
    ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'FamilyGraphVisualizer' object has no attribute 'draw_tree'
2025-08-28 01:22:45,368 - root - ERROR - Error en simulación: 'FamilyGraphVisualizer' object has no attribute 'draw_tree'
Traceback (most recent call last):
  File "c:\Users\pablo\OneDrive\Escritorio\ArbolGenealogico\gui\simulation_panel.py", line 141, in run_simulation
    self.draw_tree()
    ~~~~~~~~~~~~~~^^
  File "c:\Users\pablo\OneDrive\Escritorio\ArbolGenealogico\gui\simulation_panel.py", line 227, in draw_tree
    visualizer.draw_tree(self.simulated_family, self.tree_canvas)
    ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'FamilyGraphVisualizer' object has no attribute 'draw_tree'
2025-08-28 14:14:12,922 - matplotlib - DEBUG - matplotlib data path: C:\Users\USER\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\matplotlib\mpl-data
2025-08-28 14:14:12,977 - matplotlib - DEBUG - CONFIGDIR=C:\Users\USER\.matplotlib
2025-08-28 14:14:12,979 - matplotlib - DEBUG - interactive is False
2025-08-28 14:14:12,980 - matplotlib - DEBUG - platform is win32
2025-08-28 14:14:13,156 - root - INFO - Matplotlib backend configurado correctamente
2025-08-28 14:14:13,955 - root - INFO - CustomTkinter importado correctamente
2025-08-28 14:14:17,501 - matplotlib - DEBUG - CACHEDIR=C:\Users\USER\.matplotlib
2025-08-28 14:14:17,511 - matplotlib.font_manager - DEBUG - Using fontManager instance from C:\Users\USER\.matplotlib\fontlist-v390.json
2025-08-28 14:14:19,333 - root - INFO - Módulo gui.app importado correctamente
2025-08-28 14:14:19,334 - root - INFO - Configuración de CustomTkinter establecida
2025-08-28 14:14:19,923 - root - INFO - Ventana principal creada
2025-08-28 14:14:21,335 - root - INFO - GenealogyApp inicializada correctamente
2025-08-28 14:14:21,335 - root - INFO - Iniciando bucle principal de la aplicación...
2025-08-28 14:18:58,027 - matplotlib - DEBUG - matplotlib data path: C:\Users\USER\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\matplotlib\mpl-data
2025-08-28 14:18:58,051 - matplotlib - DEBUG - CONFIGDIR=C:\Users\USER\.matplotlib
2025-08-28 14:18:58,055 - matplotlib - DEBUG - interactive is False
2025-08-28 14:18:58,055 - matplotlib - DEBUG - platform is win32
2025-08-28 14:18:58,081 - root - INFO - Matplotlib backend configurado correctamente
2025-08-28 14:18:58,159 - root - INFO - CustomTkinter importado correctamente
2025-08-28 14:18:58,275 - root - CRITICAL - Error FATAL al importar módulos: invalid syntax (relacion_service.py, line 5)
Traceback (most recent call last):
  File "c:\Users\USER\OneDrive\Escritorio\ArbolGenealogico\main.py", line 35, in <module>
    from gui.app import GenealogyApp
  File "c:\Users\USER\OneDrive\Escritorio\ArbolGenealogico\gui\app.py", line 14, in <module>
    from services.relacion_service import RelacionService
  File "c:\Users\USER\OneDrive\Escritorio\ArbolGenealogico\services\relacion_service.py", line 5
    from utils.utils service import verificar_requisitos_union
                     ^^^^^^^
SyntaxError: invalid syntax
2025-08-28 14:36:03,160 - matplotlib - DEBUG - matplotlib data path: C:\Users\USER\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\matplotlib\mpl-data
2025-08-28 14:36:03,181 - matplotlib - DEBUG - CONFIGDIR=C:\Users\USER\.matplotlib
2025-08-28 14:36:03,184 - matplotlib - DEBUG - interactive is False
2025-08-28 14:36:03,185 - matplotlib - DEBUG - platform is win32
2025-08-28 14:36:03,205 - root - INFO - Matplotlib backend configurado correctamente
2025-08-28 14:36:03,262 - root - INFO - CustomTkinter importado correctamente
2025-08-28 14:36:03,548 - matplotlib - DEBUG - CACHEDIR=C:\Users\USER\.matplotlib
2025-08-28 14:36:03,552 - matplotlib.font_manager - DEBUG - Using fontManager instance from C:\Users\USER\.matplotlib\fontlist-v390.json
2025-08-28 14:36:03,859 - root - INFO - Módulo gui.app importado correctamente
2025-08-28 14:36:03,860 - root - INFO - Configuración de CustomTkinter establecida
2025-08-28 14:36:03,932 - root - INFO - Ventana principal creada
2025-08-28 14:36:04,395 - root - INFO - GenealogyApp inicializada correctamente
2025-08-28 14:36:04,395 - root - INFO - Iniciando bucle principal de la aplicación...
2025-08-28 18:08:02,209 - matplotlib - DEBUG - matplotlib data path: C:\Users\USER\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\matplotlib\mpl-data
2025-08-28 18:08:02,231 - matplotlib - DEBUG - CONFIGDIR=C:\Users\USER\.matplotlib
2025-08-28 18:08:02,234 - matplotlib - DEBUG - interactive is False
2025-08-28 18:08:02,235 - matplotlib - DEBUG - platform is win32
2025-08-28 18:08:02,260 - root - INFO - Matplotlib backend configurado correctamente
2025-08-28 18:08:02,331 - root - INFO - CustomTkinter importado correctamente
2025-08-28 18:08:02,876 - matplotlib - DEBUG - CACHEDIR=C:\Users\USER\.matplotlib
2025-08-28 18:08:02,881 - matplotlib.font_manager - DEBUG - Using fontManager instance from C:\Users\USER\.matplotlib\fontlist-v390.json
2025-08-28 18:08:03,196 - root - INFO - Módulo gui.app importado correctamente
2025-08-28 18:08:03,197 - root - INFO - Configuración de CustomTkinter establecida
2025-08-28 18:08:03,296 - root - INFO - Ventana principal creada
2025-08-28 18:08:03,873 - root - INFO - GenealogyApp inicializada correctamente
2025-08-28 18:08:03,873 - root - INFO - Iniciando bucle principal de la aplicación...
2025-08-28 18:17:51,044 - matplotlib - DEBUG - matplotlib data path: C:\Users\USER\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\matplotlib\mpl-data
2025-08-28 18:17:51,053 - matplotlib - DEBUG - CONFIGDIR=C:\Users\USER\.matplotlib
2025-08-28 18:17:51,055 - matplotlib - DEBUG - interactive is False
2025-08-28 18:17:51,055 - matplotlib - DEBUG - platform is win32
2025-08-28 18:17:51,071 - root - INFO - Matplotlib backend configurado correctamente
2025-08-28 18:17:51,186 - root - INFO - CustomTkinter importado correctamente
2025-08-28 18:17:51,425 - matplotlib - DEBUG - CACHEDIR=C:\Users\USER\.matplotlib
2025-08-28 18:17:51,427 - matplotlib.font_manager - DEBUG - Using fontManager instance from C:\Users\USER\.matplotlib\fontlist-v390.json
2025-08-28 18:17:51,611 - root - INFO - Módulo gui.app importado correctamente
2025-08-28 18:17:51,611 - root - INFO - Configuración de CustomTkinter establecida
2025-08-28 18:17:51,711 - root - INFO - Ventana principal creada
2025-08-28 18:17:52,272 - root - INFO - GenealogyApp inicializada correctamente
2025-08-28 18:17:52,273 - root - INFO - Iniciando bucle principal de la aplicación...
2025-08-28 18:30:21,975 - matplotlib - DEBUG - matplotlib data path: C:\Users\USER\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\matplotlib\mpl-data
2025-08-28 18:30:21,986 - matplotlib - DEBUG - CONFIGDIR=C:\Users\USER\.matplotlib
2025-08-28 18:30:21,987 - matplotlib - DEBUG - interactive is False
2025-08-28 18:30:21,987 - matplotlib - DEBUG - platform is win32
2025-08-28 18:30:22,003 - root - INFO - Matplotlib backend configurado correctamente
2025-08-28 18:30:22,132 - root - INFO - CustomTkinter importado correctamente
2025-08-28 18:30:22,475 - matplotlib - DEBUG - CACHEDIR=C:\Users\USER\.matplotlib
2025-08-28 18:30:22,478 - matplotlib.font_manager - DEBUG - Using fontManager instance from C:\Users\USER\.matplotlib\fontlist-v390.json
2025-08-28 18:30:22,687 - root - INFO - Módulo gui.app importado correctamente
2025-08-28 18:30:22,688 - root - INFO - Configuración de CustomTkinter establecida
2025-08-28 18:30:22,796 - root - INFO - Ventana principal creada
2025-08-28 18:30:23,329 - gui.simulation_panel - INFO - UI del panel de simulación configurada correctamente
2025-08-28 18:30:23,367 - root - INFO - GenealogyApp inicializada correctamente
2025-08-28 18:30:23,368 - root - INFO - Iniciando bucle principal de la aplicación...
2025-08-28 18:30:59,937 - gui.simulation_panel - ERROR - Error importando ejemplo: 'GedcomParser' object has no attribute 'parse_gedcom_file'
Traceback (most recent call last):
  File "C:\Users\USER\OneDrive\Escritorio\ArbolGenealogico\gui\simulation_panel.py", line 337, in importar_ejemplo
    ejemplo_family = parser.parse_gedcom_file(ejemplo_path)
                     ^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'GedcomParser' object has no attribute 'parse_gedcom_file'
2025-08-28 18:45:34,201 - matplotlib - DEBUG - matplotlib data path: C:\Users\USER\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\matplotlib\mpl-data
2025-08-28 18:45:34,211 - matplotlib - DEBUG - CONFIGDIR=C:\Users\USER\.matplotlib
2025-08-28 18:45:34,212 - matplotlib - DEBUG - interactive is False
2025-08-28 18:45:34,214 - matplotlib - DEBUG - platform is win32
2025-08-28 18:45:34,226 - root - INFO - Matplotlib backend configurado correctamente
2025-08-28 18:45:34,303 - root - INFO - CustomTkinter importado correctamente
2025-08-28 18:45:34,523 - matplotlib - DEBUG - CACHEDIR=C:\Users\USER\.matplotlib
2025-08-28 18:45:34,523 - matplotlib.font_manager - DEBUG - Using fontManager instance from C:\Users\USER\.matplotlib\fontlist-v390.json
2025-08-28 18:45:34,687 - root - INFO - Módulo gui.app importado correctamente
2025-08-28 18:45:34,687 - root - INFO - Configuración de CustomTkinter establecida
2025-08-28 18:45:34,770 - root - INFO - Ventana principal creada
2025-08-28 18:45:35,248 - gui.simulation_panel - INFO - UI del panel de simulación configurada correctamente
2025-08-28 18:45:35,298 - root - INFO - GenealogyApp inicializada correctamente
2025-08-28 18:45:35,298 - root - INFO - Iniciando bucle principal de la aplicación...
2025-08-28 18:53:19,094 - gui.simulation_panel - ERROR - Error importando ejemplo: 'GedcomParser' object has no attribute 'parse_gedcom_file'
Traceback (most recent call last):
  File "C:\Users\USER\OneDrive\Escritorio\ArbolGenealogico\gui\simulation_panel.py", line 337, in importar_ejemplo
    )
      
AttributeError: 'GedcomParser' object has no attribute 'parse_gedcom_file'
2025-08-28 18:53:51,117 - gui.simulation_panel - ERROR - Error importando ejemplo: 'GedcomParser' object has no attribute 'parse_gedcom_file'
Traceback (most recent call last):
  File "C:\Users\USER\OneDrive\Escritorio\ArbolGenealogico\gui\simulation_panel.py", line 337, in importar_ejemplo
    )
      
AttributeError: 'GedcomParser' object has no attribute 'parse_gedcom_file'
2025-08-28 18:57:10,127 - matplotlib - DEBUG - matplotlib data path: C:\Users\USER\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\matplotlib\mpl-data
2025-08-28 18:57:10,136 - matplotlib - DEBUG - CONFIGDIR=C:\Users\USER\.matplotlib
2025-08-28 18:57:10,137 - matplotlib - DEBUG - interactive is False
2025-08-28 18:57:10,137 - matplotlib - DEBUG - platform is win32
2025-08-28 18:57:10,149 - root - INFO - Matplotlib backend configurado correctamente
2025-08-28 18:57:10,236 - root - INFO - CustomTkinter importado correctamente
2025-08-28 18:57:10,471 - matplotlib - DEBUG - CACHEDIR=C:\Users\USER\.matplotlib
2025-08-28 18:57:10,472 - matplotlib.font_manager - DEBUG - Using fontManager instance from C:\Users\USER\.matplotlib\fontlist-v390.json
2025-08-28 18:57:10,639 - root - INFO - Módulo gui.app importado correctamente
2025-08-28 18:57:10,639 - root - INFO - Configuración de CustomTkinter establecida
2025-08-28 18:57:10,728 - root - INFO - Ventana principal creada
2025-08-28 18:57:11,132 - gui.simulation_panel - INFO - UI del panel de simulación configurada correctamente
2025-08-28 18:57:11,179 - root - INFO - GenealogyApp inicializada correctamente
2025-08-28 18:57:11,179 - root - INFO - Iniciando bucle principal de la aplicación...
2025-08-28 19:16:41,338 - matplotlib - DEBUG - matplotlib data path: C:\Users\USER\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\matplotlib\mpl-data
2025-08-28 19:16:41,358 - matplotlib - DEBUG - CONFIGDIR=C:\Users\USER\.matplotlib
2025-08-28 19:16:41,361 - matplotlib - DEBUG - interactive is False
2025-08-28 19:16:41,362 - matplotlib - DEBUG - platform is win32
2025-08-28 19:16:41,383 - root - INFO - Matplotlib backend configurado correctamente
2025-08-28 19:16:41,450 - root - INFO - CustomTkinter importado correctamente
2025-08-28 19:16:41,739 - matplotlib - DEBUG - CACHEDIR=C:\Users\USER\.matplotlib
2025-08-28 19:16:41,742 - matplotlib.font_manager - DEBUG - Using fontManager instance from C:\Users\USER\.matplotlib\fontlist-v390.json
2025-08-28 19:16:42,067 - root - INFO - Módulo gui.app importado correctamente
2025-08-28 19:16:42,068 - root - INFO - Configuración de CustomTkinter establecida
2025-08-28 19:16:42,178 - root - INFO - Ventana principal creada
2025-08-28 19:16:42,570 - gui.simulation_panel - INFO - UI del panel de simulación configurada correctamente
2025-08-28 19:16:42,644 - root - INFO - GenealogyApp inicializada correctamente
2025-08-28 19:16:42,644 - root - INFO - Iniciando bucle principal de la aplicación...
2025-08-28 19:16:59,937 - asyncio - INFO - Sofia Elena formó pareja con Miguel (persona externa)
2025-08-28 19:16:59,938 - asyncio - INFO - Nueva persona generada: Miguel Carballo, edad: 35
2025-08-28 19:16:59,940 - asyncio - INFO - Intereses comunes: ['Videojuegos', 'Libros']
2025-08-28 19:17:05,247 - asyncio - INFO - Luis Carlos formó pareja con Elena (persona externa)
2025-08-28 19:17:05,250 - asyncio - INFO - Nueva persona generada: Elena Esquivel, edad: 43
2025-08-28 19:17:05,262 - asyncio - INFO - Intereses comunes: ['Economía', 'Videojuegos']
2025-08-28 19:25:55,484 - matplotlib - DEBUG - matplotlib data path: C:\Users\USER\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\matplotlib\mpl-data
2025-08-28 19:25:55,492 - matplotlib - DEBUG - CONFIGDIR=C:\Users\USER\.matplotlib
2025-08-28 19:25:55,494 - matplotlib - DEBUG - interactive is False
2025-08-28 19:25:55,494 - matplotlib - DEBUG - platform is win32
2025-08-28 19:25:55,506 - root - INFO - Matplotlib backend configurado correctamente
2025-08-28 19:25:55,588 - root - INFO - CustomTkinter importado correctamente
2025-08-28 19:25:55,779 - matplotlib - DEBUG - CACHEDIR=C:\Users\USER\.matplotlib
2025-08-28 19:25:55,781 - matplotlib.font_manager - DEBUG - Using fontManager instance from C:\Users\USER\.matplotlib\fontlist-v390.json
2025-08-28 19:25:55,935 - root - INFO - Módulo gui.app importado correctamente
2025-08-28 19:25:55,937 - root - INFO - Configuración de CustomTkinter establecida
2025-08-28 19:25:56,017 - root - INFO - Ventana principal creada
2025-08-28 19:25:56,477 - gui.simulation_panel - INFO - UI del panel de simulación configurada correctamente
2025-08-28 19:25:56,527 - root - INFO - GenealogyApp inicializada correctamente
2025-08-28 19:25:56,527 - root - INFO - Iniciando bucle principal de la aplicación...
2025-08-28 19:26:34,040 - asyncio - INFO - Luis Carlos formó pareja con Patricia (persona externa)
2025-08-28 19:26:34,040 - asyncio - INFO - Nueva persona generada: Patricia Aguilar, edad: 36
2025-08-28 19:26:34,042 - asyncio - INFO - Intereses comunes: ['Comunidad', 'Series']
2025-08-28 19:26:35,087 - asyncio - INFO - Sofia Elena formó pareja con José (persona externa)
2025-08-28 19:26:35,087 - asyncio - INFO - Nueva persona generada: José Castro, edad: 35
2025-08-28 19:26:35,087 - asyncio - INFO - Intereses comunes: ['Eventos sociales', 'Filosofía']
2025-08-28 19:26:59,651 - asyncio - INFO - Patricia formó pareja con Diego (persona externa)
2025-08-28 19:26:59,652 - asyncio - INFO - Nueva persona generada: Diego Esquivel, edad: 22
2025-08-28 19:26:59,652 - asyncio - INFO - Intereses comunes: ['Juegos', 'Cuentos']
2025-08-28 19:27:04,734 - asyncio - INFO - Ana formó pareja con Oscar (persona externa)
2025-08-28 19:27:04,734 - asyncio - INFO - Nueva persona generada: Oscar Picado, edad: 19
2025-08-28 19:27:04,735 - asyncio - INFO - Intereses comunes: ['Música', 'Cuentos']
2025-08-28 19:27:09,604 - asyncio - INFO - Mario formó pareja con Verónica (persona externa)
2025-08-28 19:27:09,605 - asyncio - INFO - Nueva persona generada: Verónica Chaves, edad: 24
2025-08-28 19:27:09,605 - asyncio - INFO - Intereses comunes: ['Juegos', 'Dibujo']
2025-08-28 19:27:13,160 - asyncio - INFO - Luis formó pareja con Elena (persona externa)
2025-08-28 19:27:13,160 - asyncio - INFO - Nueva persona generada: Elena Salas, edad: 35
2025-08-28 19:27:13,160 - asyncio - INFO - Intereses comunes: ['Cuentos', 'Dibujo']
2025-08-28 19:27:30,027 - asyncio - INFO - Ricardo formó pareja con Paula (persona externa)
2025-08-28 19:27:30,027 - asyncio - INFO - Nueva persona generada: Paula Rojas, edad: 21
2025-08-28 19:27:30,027 - asyncio - INFO - Intereses comunes: ['Naturaleza', 'Juegos']
2025-08-28 19:27:33,389 - asyncio - INFO - Luis formó pareja con Carmen (persona externa)
2025-08-28 19:27:33,389 - asyncio - INFO - Nueva persona generada: Carmen Araya, edad: 28
2025-08-28 19:27:33,389 - asyncio - INFO - Intereses comunes: ['Cuentos', 'Música']
2025-08-28 19:27:33,389 - asyncio - INFO - Oscar formó pareja con Patricia (persona externa)
2025-08-28 19:27:33,390 - asyncio - INFO - Nueva persona generada: Patricia Cordero, edad: 21
2025-08-28 19:27:33,390 - asyncio - INFO - Intereses comunes: ['Cuentos', 'Juegos']
2025-08-28 19:27:35,687 - asyncio - INFO - Mónica formó pareja con Alberto (persona externa)
2025-08-28 19:27:35,687 - asyncio - INFO - Nueva persona generada: Alberto Solano, edad: 18
2025-08-28 19:27:35,687 - asyncio - INFO - Intereses comunes: ['Música', 'Juegos']
2025-08-28 19:27:42,770 - asyncio - INFO - Daniela formó pareja con Miguel (persona externa)
2025-08-28 19:27:42,771 - asyncio - INFO - Nueva persona generada: Miguel Trejos, edad: 18
2025-08-28 19:27:42,772 - asyncio - INFO - Intereses comunes: ['Naturaleza', 'Música']
2025-08-28 19:27:46,159 - asyncio - INFO - Paula formó pareja con Carlos (persona externa)
2025-08-28 19:27:46,159 - asyncio - INFO - Nueva persona generada: Carlos Herrera, edad: 28
2025-08-28 19:27:46,160 - asyncio - INFO - Intereses comunes: ['Naturaleza', 'Dibujo']
2025-08-28 19:27:48,605 - asyncio - INFO - Sofía formó pareja con Alberto (persona externa)
2025-08-28 19:27:48,605 - asyncio - INFO - Nueva persona generada: Alberto Mora, edad: 40
2025-08-28 19:27:48,606 - asyncio - INFO - Intereses comunes: ['Naturaleza', 'Cuentos']
2025-08-28 19:27:49,854 - asyncio - INFO - Andrés formó pareja con Claudia (persona externa)
2025-08-28 19:27:49,854 - asyncio - INFO - Nueva persona generada: Claudia Segura, edad: 39
2025-08-28 19:27:49,855 - asyncio - INFO - Intereses comunes: ['Dibujo', 'Naturaleza']
2025-08-28 19:27:51,054 - asyncio - INFO - Miguel formó pareja con Carolina (persona externa)
2025-08-28 19:27:51,055 - asyncio - INFO - Nueva persona generada: Carolina Villalobos, edad: 31
2025-08-28 19:27:51,057 - asyncio - INFO - Intereses comunes: ['Juegos', 'Dibujo']
2025-08-28 19:27:56,109 - asyncio - INFO - Claudia formó pareja con Ricardo (persona externa)
2025-08-28 19:27:56,110 - asyncio - INFO - Nueva persona generada: Ricardo Ramírez, edad: 23
2025-08-28 19:27:56,110 - asyncio - INFO - Intereses comunes: ['Naturaleza', 'Cuentos']
2025-08-28 19:27:56,111 - asyncio - INFO - Juan formó pareja con Sofía (persona externa)
2025-08-28 19:27:56,111 - asyncio - INFO - Nueva persona generada: Sofía Vega, edad: 30
2025-08-28 19:27:56,111 - asyncio - INFO - Intereses comunes: ['Juegos', 'Dibujo']
2025-08-28 19:28:04,107 - asyncio - INFO - Andrés formó pareja con Laura (persona externa)
2025-08-28 19:28:04,107 - asyncio - INFO - Nueva persona generada: Laura Quesada, edad: 23
2025-08-28 19:28:04,107 - asyncio - INFO - Intereses comunes: ['Cuentos', 'Dibujo']
2025-08-28 19:28:06,791 - asyncio - INFO - Raúl formó pareja con Gabriela (persona externa)
2025-08-28 19:28:06,792 - asyncio - INFO - Nueva persona generada: Gabriela Mendez, edad: 18
2025-08-28 19:28:06,793 - asyncio - INFO - Intereses comunes: ['Dibujo', 'Naturaleza']
2025-08-28 19:28:06,793 - asyncio - INFO - Carlos formó pareja con Mónica (persona externa)
2025-08-28 19:28:06,794 - asyncio - INFO - Nueva persona generada: Mónica Monge, edad: 18
2025-08-28 19:28:06,794 - asyncio - INFO - Intereses comunes: ['Dibujo', 'Naturaleza']
2025-08-28 19:28:08,122 - asyncio - INFO - Carmen formó pareja con Diego (persona externa)
2025-08-28 19:28:08,123 - asyncio - INFO - Nueva persona generada: Diego Carballo, edad: 19
2025-08-28 19:28:08,124 - asyncio - INFO - Intereses comunes: ['Música', 'Juegos']
2025-08-28 19:28:10,466 - asyncio - INFO - Sofía formó pareja con Víctor (persona externa)
2025-08-28 19:28:10,466 - asyncio - INFO - Nueva persona generada: Víctor Salas, edad: 21
2025-08-28 19:28:10,467 - asyncio - INFO - Intereses comunes: ['Dibujo', 'Juegos']
2025-08-28 19:28:11,795 - asyncio - INFO - Mónica formó pareja con Miguel (persona externa)
2025-08-28 19:28:11,795 - asyncio - INFO - Nueva persona generada: Miguel Rojas, edad: 38
2025-08-28 19:28:11,795 - asyncio - INFO - Intereses comunes: ['Naturaleza', 'Juegos']
2025-08-28 19:28:11,796 - asyncio - INFO - Diego formó pareja con Claudia (persona externa)
2025-08-28 19:28:11,796 - asyncio - INFO - Nueva persona generada: Claudia Monge, edad: 37
2025-08-28 19:28:11,797 - asyncio - INFO - Intereses comunes: ['Naturaleza', 'Arte']
2025-08-28 19:28:20,350 - asyncio - INFO - Raúl formó pareja con Claudia (persona externa)
2025-08-28 19:28:20,351 - asyncio - INFO - Nueva persona generada: Claudia Trejos, edad: 29
2025-08-28 19:28:20,352 - asyncio - INFO - Intereses comunes: ['Naturaleza', 'Cuentos']
2025-08-28 19:28:20,352 - asyncio - INFO - Luis formó pareja con Isabel (persona externa)
2025-08-28 19:28:20,352 - asyncio - INFO - Nueva persona generada: Isabel Segura, edad: 26
2025-08-28 19:28:20,353 - asyncio - INFO - Intereses comunes: ['Música', 'Dibujo']
2025-08-28 19:32:27,474 - matplotlib - DEBUG - matplotlib data path: C:\Users\USER\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\matplotlib\mpl-data
2025-08-28 19:32:27,475 - matplotlib - DEBUG - matplotlib data path: C:\Users\USER\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\matplotlib\mpl-data
2025-08-28 19:32:27,604 - matplotlib - DEBUG - CONFIGDIR=C:\Users\USER\.matplotlib
2025-08-28 19:32:27,605 - matplotlib - DEBUG - CONFIGDIR=C:\Users\USER\.matplotlib
2025-08-28 19:32:27,608 - matplotlib - DEBUG - interactive is False
2025-08-28 19:32:27,609 - matplotlib - DEBUG - platform is win32
2025-08-28 19:32:27,609 - matplotlib - DEBUG - interactive is False
2025-08-28 19:32:27,609 - matplotlib - DEBUG - platform is win32
2025-08-28 19:32:27,777 - root - INFO - Matplotlib backend configurado correctamente
2025-08-28 19:32:27,777 - root - INFO - Matplotlib backend configurado correctamente
2025-08-28 19:32:29,193 - root - INFO - CustomTkinter importado correctamente
2025-08-28 19:32:29,193 - root - INFO - CustomTkinter importado correctamente
2025-08-28 19:32:36,474 - matplotlib - DEBUG - CACHEDIR=C:\Users\USER\.matplotlib
2025-08-28 19:32:36,475 - matplotlib - DEBUG - CACHEDIR=C:\Users\USER\.matplotlib
2025-08-28 19:32:36,498 - matplotlib.font_manager - DEBUG - Using fontManager instance from C:\Users\USER\.matplotlib\fontlist-v390.json
2025-08-28 19:32:36,503 - matplotlib.font_manager - DEBUG - Using fontManager instance from C:\Users\USER\.matplotlib\fontlist-v390.json
2025-08-28 19:32:38,921 - root - INFO - Módulo gui.app importado correctamente
2025-08-28 19:32:38,922 - root - INFO - Configuración de CustomTkinter establecida
2025-08-28 19:32:38,922 - root - INFO - Configuración de CustomTkinter establecida
2025-08-28 19:32:40,117 - root - INFO - Ventana principal creada
2025-08-28 19:32:40,131 - root - INFO - Ventana principal creada
2025-08-28 19:32:41,880 - gui.simulation_panel - INFO - UI del panel de simulación configurada correctamente
2025-08-28 19:32:41,881 - gui.simulation_panel - INFO - UI del panel de simulación configurada correctamente
2025-08-28 19:32:41,959 - root - INFO - GenealogyApp inicializada correctamente
2025-08-28 19:32:41,959 - root - INFO - GenealogyApp inicializada correctamente
2025-08-28 19:32:41,960 - root - INFO - Iniciando bucle principal de la aplicación...
2025-08-28 19:32:41,960 - root - INFO - Iniciando bucle principal de la aplicación...
2025-08-28 19:40:32,540 - matplotlib - DEBUG - matplotlib data path: C:\Users\USER\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\matplotlib\mpl-data
2025-08-28 19:40:32,565 - matplotlib - DEBUG - CONFIGDIR=C:\Users\USER\.matplotlib
2025-08-28 19:40:32,569 - matplotlib - DEBUG - interactive is False
2025-08-28 19:40:32,570 - matplotlib - DEBUG - platform is win32
2025-08-28 19:40:32,601 - root - INFO - Matplotlib backend configurado correctamente
2025-08-28 19:40:32,695 - root - INFO - CustomTkinter importado correctamente
2025-08-28 19:40:32,979 - matplotlib - DEBUG - CACHEDIR=C:\Users\USER\.matplotlib
2025-08-28 19:40:32,982 - matplotlib.font_manager - DEBUG - Using fontManager instance from C:\Users\USER\.matplotlib\fontlist-v390.json
2025-08-28 19:40:33,345 - root - INFO - Módulo gui.app importado correctamente
2025-08-28 19:40:33,347 - root - INFO - Configuración de CustomTkinter establecida
2025-08-28 19:40:33,454 - root - INFO - Ventana principal creada
2025-08-28 19:40:33,929 - gui.simulation_panel - INFO - UI del panel de simulación configurada correctamente
2025-08-28 19:40:33,981 - root - INFO - GenealogyApp inicializada correctamente
2025-08-28 19:40:33,982 - root - INFO - Iniciando bucle principal de la aplicación...
2025-08-28 19:40:47,444 - asyncio - INFO - Sofia Elena formó pareja con Andrés (persona externa)
2025-08-28 19:40:47,445 - asyncio - INFO - Nueva persona generada: Andrés Picado, edad: 21
2025-08-28 19:40:47,445 - asyncio - INFO - Intereses comunes: ['Conciertos', 'Senderismo']
2025-08-28 19:41:46,823 - asyncio - INFO - Luis Carlos formó pareja con Claudia (persona externa)
2025-08-28 19:41:46,824 - asyncio - INFO - Nueva persona generada: Claudia Chaves, edad: 54
2025-08-28 19:41:46,825 - asyncio - INFO - Intereses comunes: ['Vinos', 'Café']
2025-08-28 19:42:48,663 - gui.simulation_panel - INFO - Árbol de simulación limpiado exitosamente
2025-08-28 19:43:08,646 - asyncio - INFO - Luis Carlos formó pareja con Ana (persona externa)
2025-08-28 19:43:08,648 - asyncio - INFO - Nueva persona generada: Ana Trejos, edad: 24
2025-08-28 19:43:08,648 - asyncio - INFO - Intereses comunes: ['Pintura', 'Terapias alternativas']
2025-08-28 19:43:08,649 - asyncio - INFO - Sofia Elena formó pareja con Carlos (persona externa)
2025-08-28 19:43:08,649 - asyncio - INFO - Nueva persona generada: Carlos Aguilar, edad: 24
2025-08-28 19:43:08,650 - asyncio - INFO - Intereses comunes: ['Mindfulness', 'Pintura']
2025-08-28 19:44:26,846 - gui.simulation_panel - INFO - Árbol de simulación limpiado exitosamente
2025-08-28 19:44:37,152 - asyncio - INFO - Sofia Elena formó pareja con Ricardo (persona externa)
2025-08-28 19:44:37,152 - asyncio - INFO - Nueva persona generada: Ricardo Vega, edad: 27
2025-08-28 19:44:37,152 - asyncio - INFO - Intereses comunes: ['Bailar', 'Conciertos']
2025-08-28 19:44:42,153 - asyncio - INFO - Luis Carlos formó pareja con Verónica (persona externa)
2025-08-28 19:44:42,154 - asyncio - INFO - Nueva persona generada: Verónica Mora, edad: 26
2025-08-28 19:44:42,156 - asyncio - INFO - Intereses comunes: ['Nutrición', 'Libros']
2025-08-28 19:45:35,460 - gui.simulation_panel - INFO - Árbol de simulación limpiado exitosamente
2025-08-28 19:49:16,597 - matplotlib - DEBUG - matplotlib data path: C:\Users\USER\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\matplotlib\mpl-data
2025-08-28 19:49:16,611 - matplotlib - DEBUG - CONFIGDIR=C:\Users\USER\.matplotlib
2025-08-28 19:49:16,612 - matplotlib - DEBUG - interactive is False
2025-08-28 19:49:16,612 - matplotlib - DEBUG - platform is win32
2025-08-28 19:49:16,628 - root - INFO - Matplotlib backend configurado correctamente
2025-08-28 19:49:16,740 - root - INFO - CustomTkinter importado correctamente
2025-08-28 19:49:17,058 - matplotlib - DEBUG - CACHEDIR=C:\Users\USER\.matplotlib
2025-08-28 19:49:17,060 - matplotlib.font_manager - DEBUG - Using fontManager instance from C:\Users\USER\.matplotlib\fontlist-v390.json
2025-08-28 19:49:17,300 - root - INFO - Módulo gui.app importado correctamente
2025-08-28 19:49:17,302 - root - INFO - Configuración de CustomTkinter establecida
2025-08-28 19:49:17,402 - root - INFO - Ventana principal creada
2025-08-28 19:49:18,047 - gui.simulation_panel - INFO - UI del panel de simulación configurada correctamente
2025-08-28 19:49:18,102 - root - INFO - GenealogyApp inicializada correctamente
2025-08-28 19:49:18,102 - root - INFO - Iniciando bucle principal de la aplicación...
2025-08-28 20:03:29,926 - matplotlib - DEBUG - matplotlib data path: C:\Users\USER\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\matplotlib\mpl-data
2025-08-28 20:03:29,938 - matplotlib - DEBUG - CONFIGDIR=C:\Users\USER\.matplotlib
2025-08-28 20:03:29,940 - matplotlib - DEBUG - interactive is False
2025-08-28 20:03:29,941 - matplotlib - DEBUG - platform is win32
2025-08-28 20:03:29,954 - root - INFO - Matplotlib backend configurado correctamente
2025-08-28 20:03:30,051 - root - INFO - CustomTkinter importado correctamente
2025-08-28 20:03:30,357 - matplotlib - DEBUG - CACHEDIR=C:\Users\USER\.matplotlib
2025-08-28 20:03:30,359 - matplotlib.font_manager - DEBUG - Using fontManager instance from C:\Users\USER\.matplotlib\fontlist-v390.json
2025-08-28 20:03:30,557 - root - INFO - Módulo gui.app importado correctamente
2025-08-28 20:03:30,559 - root - INFO - Configuración de CustomTkinter establecida
2025-08-28 20:03:30,663 - root - INFO - Ventana principal creada
2025-08-28 20:03:31,399 - gui.simulation_panel - INFO - UI del panel de simulación configurada correctamente
2025-08-28 20:03:31,468 - root - INFO - GenealogyApp inicializada correctamente
2025-08-28 20:03:31,468 - root - INFO - Iniciando bucle principal de la aplicación...
2025-08-28 20:07:48,191 - matplotlib - DEBUG - matplotlib data path: C:\Users\USER\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\matplotlib\mpl-data
2025-08-28 20:07:48,215 - matplotlib - DEBUG - CONFIGDIR=C:\Users\USER\.matplotlib
2025-08-28 20:07:48,219 - matplotlib - DEBUG - interactive is False
2025-08-28 20:07:48,219 - matplotlib - DEBUG - platform is win32
2025-08-28 20:07:48,251 - root - INFO - Matplotlib backend configurado correctamente
2025-08-28 20:07:48,431 - root - INFO - CustomTkinter importado correctamente
2025-08-28 20:07:48,789 - matplotlib - DEBUG - CACHEDIR=C:\Users\USER\.matplotlib
2025-08-28 20:07:48,792 - matplotlib.font_manager - DEBUG - Using fontManager instance from C:\Users\USER\.matplotlib\fontlist-v390.json
2025-08-28 20:07:49,154 - root - INFO - Módulo gui.app importado correctamente
2025-08-28 20:07:49,155 - root - INFO - Configuración de CustomTkinter establecida
2025-08-28 20:07:49,254 - root - INFO - Ventana principal creada
2025-08-28 20:07:49,816 - gui.simulation_panel - INFO - UI del panel de simulación configurada correctamente
2025-08-28 20:07:49,877 - root - INFO - GenealogyApp inicializada correctamente
2025-08-28 20:07:49,877 - root - INFO - Iniciando bucle principal de la aplicación...
2025-08-28 20:08:22,336 - asyncio - INFO - Luis Carlos formó pareja con Isabel (persona externa)
2025-08-28 20:08:22,337 - asyncio - INFO - Nueva persona generada: Isabel Vega, edad: 32
2025-08-28 20:08:22,337 - asyncio - INFO - Intereses comunes: ['Series', 'Electrónica']
2025-08-28 20:09:46,273 - gui.simulation_panel - INFO - Árbol de simulación limpiado exitosamente
2025-08-28 20:10:48,657 - asyncio - INFO - Luis Carlos formó pareja con Verónica (persona externa)
2025-08-28 20:10:48,659 - asyncio - INFO - Nueva persona generada: Verónica Cordero, edad: 28
2025-08-28 20:10:48,659 - asyncio - INFO - Intereses comunes: ['Libros', 'Festivales']
2025-08-28 20:30:12,157 - matplotlib - DEBUG - matplotlib data path: C:\Users\USER\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\matplotlib\mpl-data
2025-08-28 20:30:12,166 - matplotlib - DEBUG - CONFIGDIR=C:\Users\USER\.matplotlib
2025-08-28 20:30:12,168 - matplotlib - DEBUG - interactive is False
2025-08-28 20:30:12,168 - matplotlib - DEBUG - platform is win32
2025-08-28 20:30:12,182 - root - INFO - Matplotlib backend configurado correctamente
2025-08-28 20:30:12,277 - root - INFO - CustomTkinter importado correctamente
2025-08-28 20:30:12,568 - matplotlib - DEBUG - CACHEDIR=C:\Users\USER\.matplotlib
2025-08-28 20:30:12,570 - matplotlib.font_manager - DEBUG - Using fontManager instance from C:\Users\USER\.matplotlib\fontlist-v390.json
2025-08-28 20:30:12,772 - root - INFO - Módulo gui.app importado correctamente
2025-08-28 20:30:12,773 - root - INFO - Configuración de CustomTkinter establecida
2025-08-28 20:30:12,870 - root - INFO - Ventana principal creada
2025-08-28 20:30:13,533 - gui.simulation_panel - INFO - UI del panel de simulación configurada correctamente
2025-08-28 20:30:13,592 - root - INFO - GenealogyApp inicializada correctamente
2025-08-28 20:30:13,592 - root - INFO - Iniciando bucle principal de la aplicación...
2025-08-28 20:32:08,717 - matplotlib - DEBUG - matplotlib data path: C:\Users\USER\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\matplotlib\mpl-data
2025-08-28 20:32:08,749 - matplotlib - DEBUG - CONFIGDIR=C:\Users\USER\.matplotlib
2025-08-28 20:32:08,754 - matplotlib - DEBUG - interactive is False
2025-08-28 20:32:08,754 - matplotlib - DEBUG - platform is win32
2025-08-28 20:32:08,783 - root - INFO - Matplotlib backend configurado correctamente
2025-08-28 20:32:08,850 - root - INFO - CustomTkinter importado correctamente
2025-08-28 20:32:09,287 - matplotlib - DEBUG - CACHEDIR=C:\Users\USER\.matplotlib
2025-08-28 20:32:09,290 - matplotlib.font_manager - DEBUG - Using fontManager instance from C:\Users\USER\.matplotlib\fontlist-v390.json
2025-08-28 20:32:09,661 - root - INFO - Módulo gui.app importado correctamente
2025-08-28 20:32:09,661 - root - INFO - Configuración de CustomTkinter establecida
2025-08-28 20:32:09,761 - root - INFO - Ventana principal creada
2025-08-28 20:32:10,311 - gui.simulation_panel - INFO - UI del panel de simulación configurada correctamente
2025-08-28 20:32:10,360 - root - INFO - GenealogyApp inicializada correctamente
2025-08-28 20:32:10,361 - root - INFO - Iniciando bucle principal de la aplicación...
2025-08-28 20:32:21,147 - gui.simulation_panel - INFO - Árbol de simulación limpiado exitosamente
2025-08-28 20:32:28,345 - gui.simulation_panel - INFO - Árbol de simulación limpiado exitosamente
2025-08-28 20:32:51,619 - matplotlib - DEBUG - matplotlib data path: C:\Users\USER\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\matplotlib\mpl-data
2025-08-28 20:32:51,644 - matplotlib - DEBUG - CONFIGDIR=C:\Users\USER\.matplotlib
2025-08-28 20:32:51,648 - matplotlib - DEBUG - interactive is False
2025-08-28 20:32:51,648 - matplotlib - DEBUG - platform is win32
2025-08-28 20:32:51,679 - root - INFO - Matplotlib backend configurado correctamente
2025-08-28 20:32:51,742 - root - INFO - CustomTkinter importado correctamente
2025-08-28 20:32:52,043 - matplotlib - DEBUG - CACHEDIR=C:\Users\USER\.matplotlib
2025-08-28 20:32:52,047 - matplotlib.font_manager - DEBUG - Using fontManager instance from C:\Users\USER\.matplotlib\fontlist-v390.json
2025-08-28 20:32:52,428 - root - INFO - Módulo gui.app importado correctamente
2025-08-28 20:32:52,429 - root - INFO - Configuración de CustomTkinter establecida
2025-08-28 20:32:52,493 - root - INFO - Ventana principal creada
2025-08-28 20:32:52,981 - gui.simulation_panel - INFO - UI del panel de simulación configurada correctamente
2025-08-28 20:32:53,033 - root - INFO - GenealogyApp inicializada correctamente
2025-08-28 20:32:53,034 - root - INFO - Iniciando bucle principal de la aplicación...
2025-08-28 20:33:17,286 - asyncio - INFO - Sofia Elena formó pareja con Mario (persona externa)
2025-08-28 20:33:17,287 - asyncio - INFO - Nueva persona generada: Mario Quesada, edad: 23
2025-08-28 20:33:17,287 - asyncio - INFO - Intereses comunes: ['Videojuegos', 'Idiomas']
2025-08-28 20:33:18,554 - asyncio - INFO - Luis Carlos formó pareja con Carmen (persona externa)
2025-08-28 20:33:18,554 - asyncio - INFO - Nueva persona generada: Carmen Trejos, edad: 35
2025-08-28 20:33:18,554 - asyncio - INFO - Intereses comunes: ['Comida internacional', 'Vinos']
2025-08-28 20:33:47,971 - gui.simulation_panel - INFO - Árbol de simulación limpiado exitosamente
2025-08-28 20:48:18,675 - matplotlib - DEBUG - matplotlib data path: C:\Users\USER\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\matplotlib\mpl-data
2025-08-28 20:48:18,686 - matplotlib - DEBUG - CONFIGDIR=C:\Users\USER\.matplotlib
2025-08-28 20:48:18,687 - matplotlib - DEBUG - interactive is False
2025-08-28 20:48:18,687 - matplotlib - DEBUG - platform is win32
2025-08-28 20:48:18,698 - root - INFO - Matplotlib backend configurado correctamente
2025-08-28 20:48:18,777 - root - INFO - CustomTkinter importado correctamente
2025-08-28 20:48:19,006 - matplotlib - DEBUG - CACHEDIR=C:\Users\USER\.matplotlib
2025-08-28 20:48:19,007 - matplotlib.font_manager - DEBUG - Using fontManager instance from C:\Users\USER\.matplotlib\fontlist-v390.json
2025-08-28 20:48:19,190 - root - INFO - Módulo gui.app importado correctamente
2025-08-28 20:48:19,191 - root - INFO - Configuración de CustomTkinter establecida
2025-08-28 20:48:19,272 - root - INFO - Ventana principal creada
2025-08-28 20:48:19,726 - gui.simulation_panel - INFO - UI del panel de simulación configurada correctamente
2025-08-28 20:48:19,768 - root - INFO - GenealogyApp inicializada correctamente
2025-08-28 20:48:19,768 - root - INFO - Iniciando bucle principal de la aplicación...
2025-08-28 20:49:00,650 - matplotlib - DEBUG - matplotlib data path: C:\Users\USER\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\matplotlib\mpl-data
2025-08-28 20:49:00,681 - matplotlib - DEBUG - CONFIGDIR=C:\Users\USER\.matplotlib
2025-08-28 20:49:00,686 - matplotlib - DEBUG - interactive is False
2025-08-28 20:49:00,686 - matplotlib - DEBUG - platform is win32
2025-08-28 20:49:00,726 - root - INFO - Matplotlib backend configurado correctamente
2025-08-28 20:49:00,824 - root - INFO - CustomTkinter importado correctamente
2025-08-28 20:49:01,482 - matplotlib - DEBUG - CACHEDIR=C:\Users\USER\.matplotlib
2025-08-28 20:49:01,488 - matplotlib.font_manager - DEBUG - Using fontManager instance from C:\Users\USER\.matplotlib\fontlist-v390.json
2025-08-28 20:49:02,006 - root - INFO - Módulo gui.app importado correctamente
2025-08-28 20:49:02,008 - root - INFO - Configuración de CustomTkinter establecida
2025-08-28 20:49:02,133 - root - INFO - Ventana principal creada
2025-08-28 20:49:02,853 - gui.simulation_panel - INFO - UI del panel de simulación configurada correctamente
2025-08-28 20:49:02,936 - root - INFO - GenealogyApp inicializada correctamente
2025-08-28 20:49:02,937 - root - INFO - Iniciando bucle principal de la aplicación...
2025-08-28 20:52:11,068 - asyncio - INFO - Luis Carlos formó pareja con Claudia (persona externa)
2025-08-28 20:52:11,072 - asyncio - INFO - Nueva persona generada: Claudia Chaves, edad: 36
2025-08-28 20:52:11,075 - asyncio - INFO - Intereses comunes: ['Psicología', 'Comida internacional']
2025-08-28 20:52:55,938 - asyncio - INFO - Sofia Elena formó pareja con Juan (persona externa)
2025-08-28 20:52:55,942 - asyncio - INFO - Nueva persona generada: Juan Castro, edad: 40
2025-08-28 20:52:55,945 - asyncio - INFO - Intereses comunes: ['Voluntariado', 'Eventos sociales']
2025-08-28 20:53:34,969 - gui.simulation_panel - INFO - Árbol de simulación limpiado exitosamente
2025-08-28 20:53:38,996 - asyncio - INFO - Luis Carlos formó pareja con Claudia (persona externa)
2025-08-28 20:53:39,001 - asyncio - INFO - Nueva persona generada: Claudia Monge, edad: 39
2025-08-28 20:53:39,002 - asyncio - INFO - Intereses comunes: ['Videojuegos', 'Terapias alternativas']
2025-08-28 20:53:39,828 - asyncio - INFO - Sofia Elena formó pareja con Luis (persona externa)
2025-08-28 20:53:39,828 - asyncio - INFO - Nueva persona generada: Luis Mendez, edad: 30
2025-08-28 20:53:39,828 - asyncio - INFO - Intereses comunes: ['Fútbol', 'Festivales']
2025-08-28 20:55:04,896 - asyncio - INFO - Oscar formó pareja con Gabriela (persona externa)
2025-08-28 20:55:04,898 - asyncio - INFO - Nueva persona generada: Gabriela Picado, edad: 24
2025-08-28 20:55:04,899 - asyncio - INFO - Intereses comunes: ['Cuentos', 'Dibujo']
2025-08-28 20:55:10,384 - asyncio - INFO - Isabel formó pareja con Mario (persona externa)
2025-08-28 20:55:10,384 - asyncio - INFO - Nueva persona generada: Mario Mora, edad: 41
2025-08-28 20:55:10,384 - asyncio - INFO - Intereses comunes: ['Música', 'Naturaleza']
2025-08-28 20:55:28,330 - gui.simulation_panel - INFO - Árbol de simulación limpiado exitosamente
2025-08-28 21:13:03,470 - matplotlib - DEBUG - matplotlib data path: C:\Users\USER\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\matplotlib\mpl-data
2025-08-28 21:13:03,489 - matplotlib - DEBUG - CONFIGDIR=C:\Users\USER\.matplotlib
2025-08-28 21:13:03,496 - matplotlib - DEBUG - interactive is False
2025-08-28 21:13:03,497 - matplotlib - DEBUG - platform is win32
2025-08-28 21:13:03,515 - root - INFO - Matplotlib backend configurado correctamente
2025-08-28 21:13:03,616 - root - INFO - CustomTkinter importado correctamente
2025-08-28 21:13:03,908 - matplotlib - DEBUG - CACHEDIR=C:\Users\USER\.matplotlib
2025-08-28 21:13:03,911 - matplotlib.font_manager - DEBUG - Using fontManager instance from C:\Users\USER\.matplotlib\fontlist-v390.json
2025-08-28 21:13:04,102 - root - INFO - Módulo gui.app importado correctamente
2025-08-28 21:13:04,103 - root - INFO - Configuración de CustomTkinter establecida
2025-08-28 21:13:04,227 - root - INFO - Ventana principal creada
2025-08-28 21:13:04,798 - gui.simulation_panel - INFO - UI del panel de simulación configurada correctamente
2025-08-28 21:13:04,861 - root - INFO - GenealogyApp inicializada correctamente
2025-08-28 21:13:04,861 - root - INFO - Iniciando bucle principal de la aplicación...
2025-08-28 21:14:35,988 - matplotlib - DEBUG - matplotlib data path: C:\Users\USER\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\matplotlib\mpl-data
2025-08-28 21:14:36,023 - matplotlib - DEBUG - CONFIGDIR=C:\Users\USER\.matplotlib
2025-08-28 21:14:36,033 - matplotlib - DEBUG - interactive is False
2025-08-28 21:14:36,033 - matplotlib - DEBUG - platform is win32
2025-08-28 21:14:36,064 - root - INFO - Matplotlib backend configurado correctamente
2025-08-28 21:14:36,142 - root - INFO - CustomTkinter importado correctamente
2025-08-28 21:14:36,493 - matplotlib - DEBUG - CACHEDIR=C:\Users\USER\.matplotlib
2025-08-28 21:14:36,496 - matplotlib.font_manager - DEBUG - Using fontManager instance from C:\Users\USER\.matplotlib\fontlist-v390.json
2025-08-28 21:14:36,833 - root - INFO - Módulo gui.app importado correctamente
2025-08-28 21:14:36,834 - root - INFO - Configuración de CustomTkinter establecida
2025-08-28 21:14:36,958 - root - INFO - Ventana principal creada
2025-08-28 21:14:37,451 - gui.simulation_panel - INFO - UI del panel de simulación configurada correctamente
2025-08-28 21:14:37,499 - root - INFO - GenealogyApp inicializada correctamente
2025-08-28 21:14:37,500 - root - INFO - Iniciando bucle principal de la aplicación...
2025-08-28 21:18:13,956 - matplotlib - DEBUG - matplotlib data path: C:\Users\USER\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\matplotlib\mpl-data
2025-08-28 21:18:13,969 - matplotlib - DEBUG - CONFIGDIR=C:\Users\USER\.matplotlib
2025-08-28 21:18:13,970 - matplotlib - DEBUG - interactive is False
2025-08-28 21:18:13,971 - matplotlib - DEBUG - platform is win32
2025-08-28 21:18:13,988 - root - INFO - Matplotlib backend configurado correctamente
2025-08-28 21:18:14,095 - root - INFO - CustomTkinter importado correctamente
2025-08-28 21:18:14,401 - matplotlib - DEBUG - CACHEDIR=C:\Users\USER\.matplotlib
2025-08-28 21:18:14,403 - matplotlib.font_manager - DEBUG - Using fontManager instance from C:\Users\USER\.matplotlib\fontlist-v390.json
2025-08-28 21:18:14,607 - root - INFO - Módulo gui.app importado correctamente
2025-08-28 21:18:14,608 - root - INFO - Configuración de CustomTkinter establecida
2025-08-28 21:18:14,714 - root - INFO - Ventana principal creada
2025-08-28 21:18:15,295 - gui.simulation_panel - INFO - UI del panel de simulación configurada correctamente
2025-08-28 21:18:15,370 - root - INFO - GenealogyApp inicializada correctamente
2025-08-28 21:18:15,370 - root - INFO - Iniciando bucle principal de la aplicación...
2025-08-28 22:02:22,489 - matplotlib - DEBUG - matplotlib data path: C:\Users\USER\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\matplotlib\mpl-data
2025-08-28 22:02:22,684 - matplotlib - DEBUG - CONFIGDIR=C:\Users\USER\.matplotlib
2025-08-28 22:02:22,689 - matplotlib - DEBUG - interactive is False
2025-08-28 22:02:22,691 - matplotlib - DEBUG - platform is win32
2025-08-28 22:02:22,969 - root - INFO - Matplotlib backend configurado correctamente
2025-08-28 22:02:24,605 - root - INFO - CustomTkinter importado correctamente
2025-08-28 22:02:25,685 - matplotlib - DEBUG - CACHEDIR=C:\Users\USER\.matplotlib
2025-08-28 22:02:25,705 - matplotlib.font_manager - DEBUG - Using fontManager instance from C:\Users\USER\.matplotlib\fontlist-v390.json
2025-08-28 22:02:28,457 - root - INFO - Módulo gui.app importado correctamente
2025-08-28 22:02:28,458 - root - INFO - Configuración de CustomTkinter establecida
2025-08-28 22:02:29,684 - root - INFO - Ventana principal creada
2025-08-28 22:02:31,644 - gui.simulation_panel - INFO - UI del panel de simulación configurada correctamente
2025-08-28 22:02:31,896 - root - INFO - GenealogyApp inicializada correctamente
2025-08-28 22:02:31,896 - root - INFO - Iniciando bucle principal de la aplicación...
2025-08-28 22:02:57,023 - asyncio - INFO - Luis Carlos formó pareja con Verónica (persona externa)
2025-08-28 22:02:57,024 - asyncio - INFO - Nueva persona generada: Verónica Araya, edad: 37
2025-08-28 22:02:57,024 - asyncio - INFO - Intereses comunes: ['Terapias alternativas', 'Festivales']
2025-08-28 22:03:03,203 - asyncio - INFO - Sofia Elena formó pareja con Andrés (persona externa)
2025-08-28 22:03:03,203 - asyncio - INFO - Nueva persona generada: Andrés Mendez, edad: 29
2025-08-28 22:03:03,203 - asyncio - INFO - Intereses comunes: ['Yoga', 'Entrenamiento']
2025-08-28 22:03:21,118 - asyncio - INFO - Daniela formó pareja con Luis (persona externa)
2025-08-28 22:03:21,119 - asyncio - INFO - Nueva persona generada: Luis Vega, edad: 20
2025-08-28 22:03:21,119 - asyncio - INFO - Intereses comunes: ['Naturaleza', 'Cuentos']
2025-08-28 22:03:21,652 - asyncio - INFO - Ricardo formó pareja con Daniela (persona externa)
2025-08-28 22:03:21,653 - asyncio - INFO - Nueva persona generada: Daniela Salas, edad: 18
2025-08-28 22:03:21,653 - asyncio - INFO - Intereses comunes: ['Cuentos', 'Dibujo']
2025-08-28 22:03:21,820 - asyncio - INFO - Fernando formó pareja con Isabel (persona externa)
2025-08-28 22:03:21,821 - asyncio - INFO - Nueva persona generada: Isabel Monge, edad: 25
2025-08-28 22:03:21,821 - asyncio - INFO - Intereses comunes: ['Dibujo', 'Música']
2025-08-28 22:03:22,469 - asyncio - INFO - María formó pareja con Ricardo (persona externa)
2025-08-28 22:03:22,469 - asyncio - INFO - Nueva persona generada: Ricardo Ramírez, edad: 29
2025-08-28 22:03:22,470 - asyncio - INFO - Intereses comunes: ['Música', 'Dibujo']
2025-08-28 22:03:23,681 - asyncio - INFO - Claudia formó pareja con Mario (persona externa)
2025-08-28 22:03:23,682 - asyncio - INFO - Nueva persona generada: Mario Picado, edad: 38
2025-08-28 22:03:23,683 - asyncio - INFO - Intereses comunes: ['Música', 'Dibujo']
2025-08-28 22:03:23,683 - asyncio - INFO - Carmen formó pareja con Raúl (persona externa)
2025-08-28 22:03:23,683 - asyncio - INFO - Nueva persona generada: Raúl Solano, edad: 26
2025-08-28 22:03:23,684 - asyncio - INFO - Intereses comunes: ['Dibujo', 'Juegos']
2025-08-28 22:03:33,732 - asyncio - INFO - Miguel formó pareja con Elena (persona externa)
2025-08-28 22:03:33,733 - asyncio - INFO - Nueva persona generada: Elena Cordero, edad: 52
2025-08-28 22:03:33,733 - asyncio - INFO - Intereses comunes: ['Dibujo', 'Naturaleza']
2025-08-28 22:03:34,490 - asyncio - INFO - Oscar formó pareja con Patricia (persona externa)
2025-08-28 22:03:34,490 - asyncio - INFO - Nueva persona generada: Patricia Esquivel, edad: 18
2025-08-28 22:03:34,490 - asyncio - INFO - Intereses comunes: ['Naturaleza', 'Dibujo']
2025-08-28 22:03:34,491 - asyncio - INFO - Andrés formó pareja con Paula (persona externa)
2025-08-28 22:03:34,492 - asyncio - INFO - Nueva persona generada: Paula Segura, edad: 18
2025-08-28 22:03:34,492 - asyncio - INFO - Intereses comunes: ['Dibujo', 'Cuentos']
2025-08-28 22:03:39,095 - asyncio - INFO - Carolina formó pareja con Miguel (persona externa)
2025-08-28 22:03:39,096 - asyncio - INFO - Nueva persona generada: Miguel Chaves, edad: 18
2025-08-28 22:03:39,096 - asyncio - INFO - Intereses comunes: ['Dibujo', 'Música']
2025-08-28 22:03:39,432 - asyncio - INFO - Sofía formó pareja con José (persona externa)
2025-08-28 22:03:39,433 - asyncio - INFO - Nueva persona generada: José Castro, edad: 32
2025-08-28 22:03:39,433 - asyncio - INFO - Intereses comunes: ['Naturaleza', 'Cuentos']
2025-08-28 22:03:39,703 - asyncio - INFO - Mario formó pareja con Ana (persona externa)
2025-08-28 22:03:39,703 - asyncio - INFO - Nueva persona generada: Ana Villalobos, edad: 28
2025-08-28 22:03:39,703 - asyncio - INFO - Intereses comunes: ['Dibujo', 'Cuentos']
2025-08-28 22:03:39,792 - asyncio - INFO - Laura formó pareja con Diego (persona externa)
2025-08-28 22:03:39,793 - asyncio - INFO - Nueva persona generada: Diego Trejos, edad: 35
2025-08-28 22:03:39,793 - asyncio - INFO - Intereses comunes: ['Naturaleza', 'Cuentos']
2025-08-28 22:03:40,432 - asyncio - INFO - Diego formó pareja con Elena (persona externa)
2025-08-28 22:03:40,432 - asyncio - INFO - Nueva persona generada: Elena Quesada, edad: 39
2025-08-28 22:03:40,432 - asyncio - INFO - Intereses comunes: ['Juegos', 'Música']
2025-08-28 22:03:41,973 - asyncio - INFO - Ricardo formó pareja con Ana (persona externa)
2025-08-28 22:03:41,974 - asyncio - INFO - Nueva persona generada: Ana Carballo, edad: 28
2025-08-28 22:03:41,974 - asyncio - INFO - Intereses comunes: ['Cuentos', 'Naturaleza']
2025-08-28 22:03:42,088 - asyncio - INFO - Fernando formó pareja con Paula (persona externa)
2025-08-28 22:03:42,089 - asyncio - INFO - Nueva persona generada: Paula Rojas, edad: 33
2025-08-28 22:03:42,089 - asyncio - INFO - Intereses comunes: ['Naturaleza', 'Música']
2025-08-28 22:08:49,262 - matplotlib - DEBUG - matplotlib data path: C:\Users\USER\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\matplotlib\mpl-data
2025-08-28 22:08:49,276 - matplotlib - DEBUG - CONFIGDIR=C:\Users\USER\.matplotlib
2025-08-28 22:08:49,278 - matplotlib - DEBUG - interactive is False
2025-08-28 22:08:49,278 - matplotlib - DEBUG - platform is win32
2025-08-28 22:08:49,294 - root - INFO - Matplotlib backend configurado correctamente
2025-08-28 22:08:49,401 - root - INFO - CustomTkinter importado correctamente
2025-08-28 22:08:49,718 - matplotlib - DEBUG - CACHEDIR=C:\Users\USER\.matplotlib
2025-08-28 22:08:49,720 - matplotlib.font_manager - DEBUG - Using fontManager instance from C:\Users\USER\.matplotlib\fontlist-v390.json
2025-08-28 22:08:49,921 - root - INFO - Módulo gui.app importado correctamente
2025-08-28 22:08:49,922 - root - INFO - Configuración de CustomTkinter establecida
2025-08-28 22:08:50,072 - root - INFO - Ventana principal creada
2025-08-28 22:08:50,707 - gui.simulation_panel - INFO - UI del panel de simulación configurada correctamente
2025-08-28 22:08:50,783 - root - INFO - GenealogyApp inicializada correctamente
2025-08-28 22:08:50,783 - root - INFO - Iniciando bucle principal de la aplicación...
2025-08-28 22:09:01,875 - asyncio - INFO - Sofia Elena formó pareja con Ricardo (persona externa)
2025-08-28 22:09:01,876 - asyncio - INFO - Nueva persona generada: Ricardo Mora, edad: 25
2025-08-28 22:09:01,876 - asyncio - INFO - Intereses comunes: ['Inteligencia Artificial', 'Astronomía']
2025-08-28 22:09:02,304 - asyncio - INFO - Luis Carlos formó pareja con Elena (persona externa)
2025-08-28 22:09:02,305 - asyncio - INFO - Nueva persona generada: Elena Rojas, edad: 33
2025-08-28 22:09:02,306 - asyncio - INFO - Intereses comunes: ['Terapias alternativas', 'Conciertos']
2025-08-28 22:12:20,114 - matplotlib - DEBUG - matplotlib data path: C:\Users\USER\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\matplotlib\mpl-data
2025-08-28 22:12:20,134 - matplotlib - DEBUG - CONFIGDIR=C:\Users\USER\.matplotlib
2025-08-28 22:12:20,137 - matplotlib - DEBUG - interactive is False
2025-08-28 22:12:20,138 - matplotlib - DEBUG - platform is win32
2025-08-28 22:12:20,170 - root - INFO - Matplotlib backend configurado correctamente
2025-08-28 22:12:20,233 - root - INFO - CustomTkinter importado correctamente
2025-08-28 22:12:20,548 - matplotlib - DEBUG - CACHEDIR=C:\Users\USER\.matplotlib
2025-08-28 22:12:20,550 - matplotlib.font_manager - DEBUG - Using fontManager instance from C:\Users\USER\.matplotlib\fontlist-v390.json
2025-08-28 22:12:20,876 - root - INFO - Módulo gui.app importado correctamente
2025-08-28 22:12:20,876 - root - INFO - Configuración de CustomTkinter establecida
2025-08-28 22:12:20,965 - root - INFO - Ventana principal creada
2025-08-28 22:12:21,515 - gui.simulation_panel - INFO - UI del panel de simulación configurada correctamente
2025-08-28 22:12:21,572 - root - INFO - GenealogyApp inicializada correctamente
2025-08-28 22:12:21,572 - root - INFO - Iniciando bucle principal de la aplicación...
2025-08-28 22:12:34,099 - asyncio - INFO - Luis Carlos formó pareja con Carmen (persona externa)
2025-08-28 22:12:34,100 - asyncio - INFO - Nueva persona generada: Carmen Solano, edad: 35
2025-08-28 22:12:34,101 - asyncio - INFO - Intereses comunes: ['Cocina', 'Matemáticas']
2025-08-28 22:12:35,512 - asyncio - INFO - Sofia Elena formó pareja con Andrés (persona externa)
2025-08-28 22:12:35,513 - asyncio - INFO - Nueva persona generada: Andrés Aguilar, edad: 24
2025-08-28 22:12:35,514 - asyncio - INFO - Intereses comunes: ['Política', 'Eventos sociales']
2025-08-28 22:12:48,459 - gui.simulation_panel - INFO - Árbol de simulación limpiado exitosamente
2025-08-28 22:24:08,013 - matplotlib - DEBUG - matplotlib data path: C:\Users\USER\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\matplotlib\mpl-data
2025-08-28 22:24:08,029 - matplotlib - DEBUG - CONFIGDIR=C:\Users\USER\.matplotlib
2025-08-28 22:24:08,029 - matplotlib - DEBUG - interactive is False
2025-08-28 22:24:08,030 - matplotlib - DEBUG - platform is win32
2025-08-28 22:24:08,044 - root - INFO - Matplotlib backend configurado correctamente
2025-08-28 22:24:08,165 - root - INFO - CustomTkinter importado correctamente
2025-08-28 22:24:08,206 - root - CRITICAL - Error FATAL al importar módulos: unexpected indent (relacion_service.py, line 283)
Traceback (most recent call last):
  File "C:\Users\USER\OneDrive\Escritorio\ArbolGenealogico\main.py", line 35, in <module>
    from gui.app import GenealogyApp
  File "C:\Users\USER\OneDrive\Escritorio\ArbolGenealogico\gui\app.py", line 14, in <module>
    from services.relacion_service import RelacionService
  File "C:\Users\USER\OneDrive\Escritorio\ArbolGenealogico\services\relacion_service.py", line 283
    if child not in father.children:
IndentationError: unexpected indent
2025-08-28 22:24:58,370 - matplotlib - DEBUG - matplotlib data path: C:\Users\USER\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\matplotlib\mpl-data
2025-08-28 22:24:58,380 - matplotlib - DEBUG - CONFIGDIR=C:\Users\USER\.matplotlib
2025-08-28 22:24:58,382 - matplotlib - DEBUG - interactive is False
2025-08-28 22:24:58,382 - matplotlib - DEBUG - platform is win32
2025-08-28 22:24:58,393 - root - INFO - Matplotlib backend configurado correctamente
2025-08-28 22:24:58,495 - root - INFO - CustomTkinter importado correctamente
2025-08-28 22:24:58,793 - matplotlib - DEBUG - CACHEDIR=C:\Users\USER\.matplotlib
2025-08-28 22:24:58,795 - matplotlib.font_manager - DEBUG - Using fontManager instance from C:\Users\USER\.matplotlib\fontlist-v390.json
2025-08-28 22:24:59,003 - root - INFO - Módulo gui.app importado correctamente
2025-08-28 22:24:59,003 - root - INFO - Configuración de CustomTkinter establecida
2025-08-28 22:24:59,109 - root - INFO - Ventana principal creada
2025-08-28 22:24:59,676 - gui.simulation_panel - INFO - UI del panel de simulación configurada correctamente
2025-08-28 22:24:59,774 - root - INFO - GenealogyApp inicializada correctamente
2025-08-28 22:24:59,774 - root - INFO - Iniciando bucle principal de la aplicación...
2025-08-28 22:34:07,455 - matplotlib - DEBUG - matplotlib data path: C:\Users\USER\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\matplotlib\mpl-data
2025-08-28 22:34:07,465 - matplotlib - DEBUG - CONFIGDIR=C:\Users\USER\.matplotlib
2025-08-28 22:34:07,467 - matplotlib - DEBUG - interactive is False
2025-08-28 22:34:07,467 - matplotlib - DEBUG - platform is win32
2025-08-28 22:34:07,489 - root - INFO - Matplotlib backend configurado correctamente
2025-08-28 22:34:07,630 - root - INFO - CustomTkinter importado correctamente
2025-08-28 22:34:08,019 - matplotlib - DEBUG - CACHEDIR=C:\Users\USER\.matplotlib
2025-08-28 22:34:08,020 - matplotlib.font_manager - DEBUG - Using fontManager instance from C:\Users\USER\.matplotlib\fontlist-v390.json
2025-08-28 22:34:08,274 - root - INFO - Módulo gui.app importado correctamente
2025-08-28 22:34:08,275 - root - INFO - Configuración de CustomTkinter establecida
2025-08-28 22:34:08,430 - root - INFO - Ventana principal creada
2025-08-28 22:34:08,982 - gui.simulation_panel - INFO - UI del panel de simulación configurada correctamente
2025-08-28 22:34:09,139 - root - INFO - GenealogyApp inicializada correctamente
2025-08-28 22:34:09,140 - root - INFO - Iniciando bucle principal de la aplicación...
2025-08-28 22:36:31,912 - matplotlib - DEBUG - matplotlib data path: C:\Users\USER\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\matplotlib\mpl-data
2025-08-28 22:36:31,921 - matplotlib - DEBUG - CONFIGDIR=C:\Users\USER\.matplotlib
2025-08-28 22:36:31,922 - matplotlib - DEBUG - interactive is False
2025-08-28 22:36:31,923 - matplotlib - DEBUG - platform is win32
2025-08-28 22:36:31,937 - root - INFO - Matplotlib backend configurado correctamente
2025-08-28 22:36:32,037 - root - INFO - CustomTkinter importado correctamente
2025-08-28 22:36:32,284 - matplotlib - DEBUG - CACHEDIR=C:\Users\USER\.matplotlib
2025-08-28 22:36:32,286 - matplotlib.font_manager - DEBUG - Using fontManager instance from C:\Users\USER\.matplotlib\fontlist-v390.json
2025-08-28 22:36:32,476 - root - INFO - Módulo gui.app importado correctamente
2025-08-28 22:36:32,476 - root - INFO - Configuración de CustomTkinter establecida
2025-08-28 22:36:32,611 - root - INFO - Ventana principal creada
2025-08-28 22:36:33,137 - gui.simulation_panel - INFO - UI del panel de simulación configurada correctamente
2025-08-28 22:36:33,358 - root - INFO - GenealogyApp inicializada correctamente
2025-08-28 22:36:33,358 - root - INFO - Iniciando bucle principal de la aplicación...
2025-08-28 22:41:28,623 - matplotlib - DEBUG - matplotlib data path: C:\Users\USER\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\matplotlib\mpl-data
2025-08-28 22:41:28,635 - matplotlib - DEBUG - CONFIGDIR=C:\Users\USER\.matplotlib
2025-08-28 22:41:28,636 - matplotlib - DEBUG - interactive is False
2025-08-28 22:41:28,636 - matplotlib - DEBUG - platform is win32
2025-08-28 22:41:28,650 - root - INFO - Matplotlib backend configurado correctamente
2025-08-28 22:41:28,772 - root - INFO - CustomTkinter importado correctamente
2025-08-28 22:41:29,137 - matplotlib - DEBUG - CACHEDIR=C:\Users\USER\.matplotlib
2025-08-28 22:41:29,139 - matplotlib.font_manager - DEBUG - Using fontManager instance from C:\Users\USER\.matplotlib\fontlist-v390.json
2025-08-28 22:41:29,350 - root - INFO - Módulo gui.app importado correctamente
2025-08-28 22:41:29,351 - root - INFO - Configuración de CustomTkinter establecida
2025-08-28 22:41:29,463 - root - INFO - Ventana principal creada
2025-08-28 22:41:30,074 - gui.simulation_panel - INFO - UI del panel de simulación configurada correctamente
2025-08-28 22:41:30,222 - root - INFO - GenealogyApp inicializada correctamente
2025-08-28 22:41:30,222 - root - INFO - Iniciando bucle principal de la aplicación...
2025-08-28 22:43:53,418 - matplotlib - DEBUG - matplotlib data path: C:\Users\USER\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\matplotlib\mpl-data
2025-08-28 22:43:53,443 - matplotlib - DEBUG - CONFIGDIR=C:\Users\USER\.matplotlib
2025-08-28 22:43:53,447 - matplotlib - DEBUG - interactive is False
2025-08-28 22:43:53,448 - matplotlib - DEBUG - platform is win32
2025-08-28 22:43:53,483 - root - INFO - Matplotlib backend configurado correctamente
2025-08-28 22:43:53,583 - root - INFO - CustomTkinter importado correctamente
2025-08-28 22:43:54,285 - matplotlib - DEBUG - CACHEDIR=C:\Users\USER\.matplotlib
2025-08-28 22:43:54,288 - matplotlib.font_manager - DEBUG - Using fontManager instance from C:\Users\USER\.matplotlib\fontlist-v390.json
2025-08-28 22:43:54,617 - root - INFO - Módulo gui.app importado correctamente
2025-08-28 22:43:54,618 - root - INFO - Configuración de CustomTkinter establecida
2025-08-28 22:43:54,679 - root - INFO - Ventana principal creada
2025-08-28 22:43:55,676 - gui.simulation_panel - INFO - UI del panel de simulación configurada correctamente
2025-08-28 22:43:55,881 - root - INFO - GenealogyApp inicializada correctamente
2025-08-28 22:43:55,881 - root - INFO - Iniciando bucle principal de la aplicación...
2025-08-28 22:50:50,376 - matplotlib - DEBUG - matplotlib data path: C:\Users\USER\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\matplotlib\mpl-data
2025-08-28 22:50:50,387 - matplotlib - DEBUG - CONFIGDIR=C:\Users\USER\.matplotlib
2025-08-28 22:50:50,388 - matplotlib - DEBUG - interactive is False
2025-08-28 22:50:50,389 - matplotlib - DEBUG - platform is win32
2025-08-28 22:50:50,401 - root - INFO - Matplotlib backend configurado correctamente
2025-08-28 22:50:50,528 - root - INFO - CustomTkinter importado correctamente
2025-08-28 22:50:50,824 - matplotlib - DEBUG - CACHEDIR=C:\Users\USER\.matplotlib
2025-08-28 22:50:50,825 - matplotlib.font_manager - DEBUG - Using fontManager instance from C:\Users\USER\.matplotlib\fontlist-v390.json
2025-08-28 22:50:51,023 - root - INFO - Módulo gui.app importado correctamente
2025-08-28 22:50:51,024 - root - INFO - Configuración de CustomTkinter establecida
2025-08-28 22:50:51,200 - root - INFO - Ventana principal creada
2025-08-28 22:50:51,713 - gui.simulation_panel - INFO - UI del panel de simulación configurada correctamente
2025-08-28 22:50:51,938 - root - INFO - GenealogyApp inicializada correctamente
2025-08-28 22:50:51,938 - root - INFO - Iniciando bucle principal de la aplicación...
2025-08-28 22:52:10,897 - matplotlib - DEBUG - matplotlib data path: C:\Users\USER\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\matplotlib\mpl-data
2025-08-28 22:52:10,911 - matplotlib - DEBUG - CONFIGDIR=C:\Users\USER\.matplotlib
2025-08-28 22:52:10,915 - matplotlib - DEBUG - interactive is False
2025-08-28 22:52:10,916 - matplotlib - DEBUG - platform is win32
2025-08-28 22:52:10,939 - root - INFO - Matplotlib backend configurado correctamente
2025-08-28 22:52:11,102 - root - INFO - CustomTkinter importado correctamente
2025-08-28 22:52:11,481 - matplotlib - DEBUG - CACHEDIR=C:\Users\USER\.matplotlib
2025-08-28 22:52:11,485 - matplotlib.font_manager - DEBUG - Using fontManager instance from C:\Users\USER\.matplotlib\fontlist-v390.json
2025-08-28 22:52:11,752 - root - INFO - Módulo gui.app importado correctamente
2025-08-28 22:52:11,754 - root - INFO - Configuración de CustomTkinter establecida
2025-08-28 22:52:11,909 - root - INFO - Ventana principal creada
2025-08-28 22:52:12,418 - gui.simulation_panel - INFO - UI del panel de simulación configurada correctamente
2025-08-28 22:52:12,625 - root - INFO - GenealogyApp inicializada correctamente
2025-08-28 22:52:12,625 - root - INFO - Iniciando bucle principal de la aplicación...
2025-08-28 22:54:43,691 - matplotlib - DEBUG - matplotlib data path: C:\Users\USER\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\matplotlib\mpl-data
2025-08-28 22:54:43,710 - matplotlib - DEBUG - CONFIGDIR=C:\Users\USER\.matplotlib
2025-08-28 22:54:43,711 - matplotlib - DEBUG - interactive is False
2025-08-28 22:54:43,711 - matplotlib - DEBUG - platform is win32
2025-08-28 22:54:43,726 - root - INFO - Matplotlib backend configurado correctamente
2025-08-28 22:54:43,876 - root - INFO - CustomTkinter importado correctamente
2025-08-28 22:54:44,175 - matplotlib - DEBUG - CACHEDIR=C:\Users\USER\.matplotlib
2025-08-28 22:54:44,176 - matplotlib.font_manager - DEBUG - Using fontManager instance from C:\Users\USER\.matplotlib\fontlist-v390.json
2025-08-28 22:54:44,412 - root - INFO - Módulo gui.app importado correctamente
2025-08-28 22:54:44,413 - root - INFO - Configuración de CustomTkinter establecida
2025-08-28 22:54:44,600 - root - INFO - Ventana principal creada
2025-08-28 22:54:45,133 - gui.simulation_panel - INFO - UI del panel de simulación configurada correctamente
2025-08-28 22:54:45,332 - root - INFO - GenealogyApp inicializada correctamente
2025-08-28 22:54:45,332 - root - INFO - Iniciando bucle principal de la aplicación...
2025-08-28 23:00:06,992 - matplotlib - DEBUG - matplotlib data path: C:\Users\USER\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\matplotlib\mpl-data
2025-08-28 23:00:07,020 - matplotlib - DEBUG - CONFIGDIR=C:\Users\USER\.matplotlib
2025-08-28 23:00:07,024 - matplotlib - DEBUG - interactive is False
2025-08-28 23:00:07,025 - matplotlib - DEBUG - platform is win32
2025-08-28 23:00:07,049 - root - INFO - Matplotlib backend configurado correctamente
2025-08-28 23:00:07,138 - root - INFO - CustomTkinter importado correctamente
2025-08-28 23:00:07,388 - matplotlib - DEBUG - CACHEDIR=C:\Users\USER\.matplotlib
2025-08-28 23:00:07,390 - matplotlib.font_manager - DEBUG - Using fontManager instance from C:\Users\USER\.matplotlib\fontlist-v390.json
2025-08-28 23:00:07,602 - root - INFO - Módulo gui.app importado correctamente
2025-08-28 23:00:07,604 - root - INFO - Configuración de CustomTkinter establecida
2025-08-28 23:00:07,760 - root - INFO - Ventana principal creada
2025-08-28 23:00:08,356 - gui.simulation_panel - INFO - UI del panel de simulación configurada correctamente
2025-08-28 23:00:08,581 - root - INFO - GenealogyApp inicializada correctamente
2025-08-28 23:00:08,582 - root - INFO - Iniciando bucle principal de la aplicación...
2025-08-29 21:57:29,375 - matplotlib - DEBUG - matplotlib data path: C:\Users\USER\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\matplotlib\mpl-data
2025-08-29 21:57:29,465 - matplotlib - DEBUG - CONFIGDIR=C:\Users\USER\.matplotlib
2025-08-29 21:57:29,468 - matplotlib - DEBUG - interactive is False
2025-08-29 21:57:29,468 - matplotlib - DEBUG - platform is win32
2025-08-29 21:57:29,646 - root - INFO - Matplotlib backend configurado correctamente
2025-08-29 21:57:30,423 - root - INFO - CustomTkinter importado correctamente
2025-08-29 21:57:34,152 - matplotlib - DEBUG - CACHEDIR=C:\Users\USER\.matplotlib
2025-08-29 21:57:34,162 - matplotlib.font_manager - DEBUG - Using fontManager instance from C:\Users\USER\.matplotlib\fontlist-v390.json
2025-08-29 21:57:35,875 - root - INFO - Módulo gui.app importado correctamente
2025-08-29 21:57:35,877 - root - INFO - Configuración de CustomTkinter establecida
2025-08-29 21:57:36,552 - root - INFO - Ventana principal creada
2025-08-29 21:57:38,225 - gui.simulation_panel - INFO - UI del panel de simulación configurada correctamente
2025-08-29 21:57:38,412 - root - INFO - GenealogyApp inicializada correctamente
2025-08-29 21:57:38,412 - root - INFO - Iniciando bucle principal de la aplicación...
2025-08-29 21:58:53,910 - matplotlib - DEBUG - matplotlib data path: C:\Users\USER\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\matplotlib\mpl-data
2025-08-29 21:58:53,940 - matplotlib - DEBUG - CONFIGDIR=C:\Users\USER\.matplotlib
2025-08-29 21:58:53,943 - matplotlib - DEBUG - interactive is False
2025-08-29 21:58:53,944 - matplotlib - DEBUG - platform is win32
2025-08-29 21:58:53,978 - root - INFO - Matplotlib backend configurado correctamente
2025-08-29 21:58:54,054 - root - INFO - CustomTkinter importado correctamente
2025-08-29 21:58:54,363 - matplotlib - DEBUG - CACHEDIR=C:\Users\USER\.matplotlib
2025-08-29 21:58:54,366 - matplotlib.font_manager - DEBUG - Using fontManager instance from C:\Users\USER\.matplotlib\fontlist-v390.json
2025-08-29 21:58:54,691 - root - INFO - Módulo gui.app importado correctamente
2025-08-29 21:58:54,692 - root - INFO - Configuración de CustomTkinter establecida
2025-08-29 21:58:54,775 - root - INFO - Ventana principal creada
2025-08-29 21:58:55,324 - gui.simulation_panel - INFO - UI del panel de simulación configurada correctamente
2025-08-29 21:58:55,485 - root - INFO - GenealogyApp inicializada correctamente
2025-08-29 21:58:55,485 - root - INFO - Iniciando bucle principal de la aplicación...
2025-08-29 22:07:08,743 - matplotlib - DEBUG - matplotlib data path: C:\Users\USER\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\matplotlib\mpl-data
2025-08-29 22:07:08,755 - matplotlib - DEBUG - CONFIGDIR=C:\Users\USER\.matplotlib
2025-08-29 22:07:08,757 - matplotlib - DEBUG - interactive is False
2025-08-29 22:07:08,757 - matplotlib - DEBUG - platform is win32
2025-08-29 22:07:08,773 - root - INFO - Matplotlib backend configurado correctamente
2025-08-29 22:07:08,904 - root - INFO - CustomTkinter importado correctamente
2025-08-29 22:07:09,289 - matplotlib - DEBUG - CACHEDIR=C:\Users\USER\.matplotlib
2025-08-29 22:07:09,292 - matplotlib.font_manager - DEBUG - Using fontManager instance from C:\Users\USER\.matplotlib\fontlist-v390.json
2025-08-29 22:07:09,487 - root - INFO - Módulo gui.app importado correctamente
2025-08-29 22:07:09,487 - root - INFO - Configuración de CustomTkinter establecida
2025-08-29 22:07:09,592 - root - INFO - Ventana principal creada
2025-08-29 22:07:10,475 - gui.simulation_panel - INFO - UI del panel de simulación configurada correctamente
2025-08-29 22:07:10,648 - root - INFO - GenealogyApp inicializada correctamente
2025-08-29 22:07:10,649 - root - INFO - Iniciando bucle principal de la aplicación...
2025-08-29 22:13:14,261 - matplotlib - DEBUG - matplotlib data path: C:\Users\USER\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\matplotlib\mpl-data
2025-08-29 22:13:14,271 - matplotlib - DEBUG - CONFIGDIR=C:\Users\USER\.matplotlib
2025-08-29 22:13:14,272 - matplotlib - DEBUG - interactive is False
2025-08-29 22:13:14,272 - matplotlib - DEBUG - platform is win32
2025-08-29 22:13:14,285 - root - INFO - Matplotlib backend configurado correctamente
2025-08-29 22:13:14,376 - root - INFO - CustomTkinter importado correctamente
2025-08-29 22:13:14,695 - matplotlib - DEBUG - CACHEDIR=C:\Users\USER\.matplotlib
2025-08-29 22:13:14,698 - matplotlib.font_manager - DEBUG - Using fontManager instance from C:\Users\USER\.matplotlib\fontlist-v390.json
2025-08-29 22:13:14,907 - root - INFO - Módulo gui.app importado correctamente
2025-08-29 22:13:14,907 - root - INFO - Configuración de CustomTkinter establecida
2025-08-29 22:13:15,026 - root - INFO - Ventana principal creada
2025-08-29 22:13:15,827 - gui.simulation_panel - INFO - UI del panel de simulación configurada correctamente
2025-08-29 22:13:15,968 - root - INFO - GenealogyApp inicializada correctamente
2025-08-29 22:13:15,969 - root - INFO - Iniciando bucle principal de la aplicación...
2025-08-29 22:14:51,250 - matplotlib - DEBUG - matplotlib data path: C:\Users\USER\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\matplotlib\mpl-data
2025-08-29 22:14:51,281 - matplotlib - DEBUG - CONFIGDIR=C:\Users\USER\.matplotlib
2025-08-29 22:14:51,285 - matplotlib - DEBUG - interactive is False
2025-08-29 22:14:51,286 - matplotlib - DEBUG - platform is win32
2025-08-29 22:14:51,321 - root - INFO - Matplotlib backend configurado correctamente
2025-08-29 22:14:51,398 - root - INFO - CustomTkinter importado correctamente
2025-08-29 22:14:51,792 - matplotlib - DEBUG - CACHEDIR=C:\Users\USER\.matplotlib
2025-08-29 22:14:51,795 - matplotlib.font_manager - DEBUG - Using fontManager instance from C:\Users\USER\.matplotlib\fontlist-v390.json
2025-08-29 22:14:52,151 - root - INFO - Módulo gui.app importado correctamente
2025-08-29 22:14:52,152 - root - INFO - Configuración de CustomTkinter establecida
2025-08-29 22:14:52,245 - root - INFO - Ventana principal creada
2025-08-29 22:14:53,145 - gui.simulation_panel - INFO - UI del panel de simulación configurada correctamente
2025-08-29 22:14:53,274 - root - INFO - GenealogyApp inicializada correctamente
2025-08-29 22:14:53,274 - root - INFO - Iniciando bucle principal de la aplicación...
2025-08-29 22:21:31,579 - matplotlib - DEBUG - matplotlib data path: C:\Users\USER\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\matplotlib\mpl-data
2025-08-29 22:21:31,588 - matplotlib - DEBUG - CONFIGDIR=C:\Users\USER\.matplotlib
2025-08-29 22:21:31,589 - matplotlib - DEBUG - interactive is False
2025-08-29 22:21:31,590 - matplotlib - DEBUG - platform is win32
2025-08-29 22:21:31,603 - root - INFO - Matplotlib backend configurado correctamente
2025-08-29 22:21:31,734 - root - INFO - CustomTkinter importado correctamente
2025-08-29 22:21:32,146 - matplotlib - DEBUG - CACHEDIR=C:\Users\USER\.matplotlib
2025-08-29 22:21:32,150 - matplotlib.font_manager - DEBUG - Using fontManager instance from C:\Users\USER\.matplotlib\fontlist-v390.json
2025-08-29 22:21:32,351 - root - INFO - Módulo gui.app importado correctamente
2025-08-29 22:21:32,353 - root - INFO - Configuración de CustomTkinter establecida
2025-08-29 22:21:32,470 - root - INFO - Ventana principal creada
2025-08-29 22:21:33,309 - gui.simulation_panel - INFO - UI del panel de simulación configurada correctamente
2025-08-29 22:21:33,477 - root - INFO - GenealogyApp inicializada correctamente
2025-08-29 22:21:33,478 - root - INFO - Iniciando bucle principal de la aplicación...
2025-08-29 22:23:20,736 - matplotlib - DEBUG - matplotlib data path: C:\Users\USER\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\matplotlib\mpl-data
2025-08-29 22:23:20,759 - matplotlib - DEBUG - CONFIGDIR=C:\Users\USER\.matplotlib
2025-08-29 22:23:20,762 - matplotlib - DEBUG - interactive is False
2025-08-29 22:23:20,763 - matplotlib - DEBUG - platform is win32
2025-08-29 22:23:20,791 - root - INFO - Matplotlib backend configurado correctamente
2025-08-29 22:23:20,866 - root - INFO - CustomTkinter importado correctamente
2025-08-29 22:23:21,240 - matplotlib - DEBUG - CACHEDIR=C:\Users\USER\.matplotlib
2025-08-29 22:23:21,243 - matplotlib.font_manager - DEBUG - Using fontManager instance from C:\Users\USER\.matplotlib\fontlist-v390.json
2025-08-29 22:23:21,595 - root - INFO - Módulo gui.app importado correctamente
2025-08-29 22:23:21,595 - root - INFO - Configuración de CustomTkinter establecida
2025-08-29 22:23:21,682 - root - INFO - Ventana principal creada
2025-08-29 22:23:22,473 - gui.simulation_panel - INFO - UI del panel de simulación configurada correctamente
2025-08-29 22:23:22,605 - root - INFO - GenealogyApp inicializada correctamente
2025-08-29 22:23:22,606 - root - INFO - Iniciando bucle principal de la aplicación...
2025-08-29 22:27:22,044 - matplotlib - DEBUG - matplotlib data path: C:\Users\USER\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\matplotlib\mpl-data
2025-08-29 22:27:22,058 - matplotlib - DEBUG - CONFIGDIR=C:\Users\USER\.matplotlib
2025-08-29 22:27:22,059 - matplotlib - DEBUG - interactive is False
2025-08-29 22:27:22,060 - matplotlib - DEBUG - platform is win32
2025-08-29 22:27:22,107 - root - INFO - Matplotlib backend configurado correctamente
2025-08-29 22:27:22,232 - root - INFO - CustomTkinter importado correctamente
2025-08-29 22:27:22,692 - matplotlib - DEBUG - CACHEDIR=C:\Users\USER\.matplotlib
2025-08-29 22:27:22,693 - matplotlib.font_manager - DEBUG - Using fontManager instance from C:\Users\USER\.matplotlib\fontlist-v390.json
2025-08-29 22:27:22,906 - root - INFO - Módulo gui.app importado correctamente
2025-08-29 22:27:22,908 - root - INFO - Configuración de CustomTkinter establecida
2025-08-29 22:27:23,025 - root - INFO - Ventana principal creada
2025-08-29 22:27:24,661 - gui.simulation_panel - INFO - UI del panel de simulación configurada correctamente
2025-08-29 22:27:24,866 - root - INFO - GenealogyApp inicializada correctamente
2025-08-29 22:27:24,866 - root - INFO - Iniciando bucle principal de la aplicación...
2025-08-29 22:29:20,914 - matplotlib - DEBUG - matplotlib data path: C:\Users\USER\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\matplotlib\mpl-data
2025-08-29 22:29:20,928 - matplotlib - DEBUG - CONFIGDIR=C:\Users\USER\.matplotlib
2025-08-29 22:29:20,929 - matplotlib - DEBUG - interactive is False
2025-08-29 22:29:20,929 - matplotlib - DEBUG - platform is win32
2025-08-29 22:29:20,948 - root - INFO - Matplotlib backend configurado correctamente
2025-08-29 22:29:21,083 - root - INFO - CustomTkinter importado correctamente
2025-08-29 22:29:21,418 - matplotlib - DEBUG - CACHEDIR=C:\Users\USER\.matplotlib
2025-08-29 22:29:21,420 - matplotlib.font_manager - DEBUG - Using fontManager instance from C:\Users\USER\.matplotlib\fontlist-v390.json
2025-08-29 22:29:21,623 - root - INFO - Módulo gui.app importado correctamente
2025-08-29 22:29:21,624 - root - INFO - Configuración de CustomTkinter establecida
2025-08-29 22:29:21,729 - root - INFO - Ventana principal creada
2025-08-29 22:29:22,652 - gui.simulation_panel - INFO - UI del panel de simulación configurada correctamente
2025-08-29 22:29:22,785 - root - INFO - GenealogyApp inicializada correctamente
2025-08-29 22:29:22,786 - root - INFO - Iniciando bucle principal de la aplicación...
2025-08-29 22:30:56,434 - matplotlib - DEBUG - matplotlib data path: C:\Users\USER\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\matplotlib\mpl-data
2025-08-29 22:30:56,463 - matplotlib - DEBUG - CONFIGDIR=C:\Users\USER\.matplotlib
2025-08-29 22:30:56,468 - matplotlib - DEBUG - interactive is False
2025-08-29 22:30:56,468 - matplotlib - DEBUG - platform is win32
2025-08-29 22:30:56,507 - root - INFO - Matplotlib backend configurado correctamente
2025-08-29 22:30:56,580 - root - INFO - CustomTkinter importado correctamente
2025-08-29 22:30:56,929 - matplotlib - DEBUG - CACHEDIR=C:\Users\USER\.matplotlib
2025-08-29 22:30:56,932 - matplotlib.font_manager - DEBUG - Using fontManager instance from C:\Users\USER\.matplotlib\fontlist-v390.json
2025-08-29 22:30:57,382 - root - INFO - Módulo gui.app importado correctamente
2025-08-29 22:30:57,383 - root - INFO - Configuración de CustomTkinter establecida
2025-08-29 22:30:57,525 - root - INFO - Ventana principal creada
2025-08-29 22:30:58,441 - gui.simulation_panel - INFO - UI del panel de simulación configurada correctamente
2025-08-29 22:30:58,537 - root - ERROR - Error de atributo: probablemente uso incorrecto de métodos o propiedades
2025-08-29 22:30:58,537 - root - ERROR - Detalles: 'ConsultasPanel' object has no attribute 'update_idletasks'
2025-08-29 22:30:58,537 - root - ERROR - Posible causa: uso de calculate_age() en lugar de calculate_virtual_age()
2025-08-29 22:30:58,537 - root - ERROR - Verifica los archivos simulation_panel.py y person.py
2025-08-29 22:30:58,537 - root - ERROR - Error crítico al iniciar la aplicación: 'ConsultasPanel' object has no attribute 'update_idletasks'
Traceback (most recent call last):
  File "c:\Users\USER\OneDrive\Escritorio\ArbolGenealogico\main.py", line 70, in <module>
    app = GenealogyApp(root)
          ^^^^^^^^^^^^^^^^^^
  File "c:\Users\USER\OneDrive\Escritorio\ArbolGenealogico\gui\app.py", line 60, in __init__
    self.create_widgets()
  File "c:\Users\USER\OneDrive\Escritorio\ArbolGenealogico\gui\app.py", line 82, in create_widgets
    self.setup_consultas_tab()
  File "c:\Users\USER\OneDrive\Escritorio\ArbolGenealogico\gui\app.py", line 95, in setup_consultas_tab
    self.consultas_panel = ConsultasPanel(self.consultas_tab, self.family)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\USER\OneDrive\Escritorio\ArbolGenealogico\gui\consultas_panel.py", line 14, in __init__
    self.setup_ui()
  File "c:\Users\USER\OneDrive\Escritorio\ArbolGenealogico\gui\consultas_panel.py", line 24, in setup_ui
    self.setup_main_content()
  File "c:\Users\USER\OneDrive\Escritorio\ArbolGenealogico\gui\consultas_panel.py", line 83, in setup_main_content
    self.setup_control_panel(left_frame)
  File "c:\Users\USER\OneDrive\Escritorio\ArbolGenealogico\gui\consultas_panel.py", line 104, in setup_control_panel
    self.setup_person_selector(parent)
  File "c:\Users\USER\OneDrive\Escritorio\ArbolGenealogico\gui\consultas_panel.py", line 175, in setup_person_selector
    self.actualizar_lista_personas()
  File "c:\Users\USER\OneDrive\Escritorio\ArbolGenealogico\gui\consultas_panel.py", line 377, in actualizar_lista_personas
    self.update_idletasks()
    ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ConsultasPanel' object has no attribute 'update_idletasks'
2025-08-29 22:32:19,587 - matplotlib - DEBUG - matplotlib data path: C:\Users\USER\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\matplotlib\mpl-data
2025-08-29 22:32:19,598 - matplotlib - DEBUG - CONFIGDIR=C:\Users\USER\.matplotlib
2025-08-29 22:32:19,600 - matplotlib - DEBUG - interactive is False
2025-08-29 22:32:19,600 - matplotlib - DEBUG - platform is win32
2025-08-29 22:32:19,620 - root - INFO - Matplotlib backend configurado correctamente
2025-08-29 22:32:19,735 - root - INFO - CustomTkinter importado correctamente
2025-08-29 22:32:20,002 - matplotlib - DEBUG - CACHEDIR=C:\Users\USER\.matplotlib
2025-08-29 22:32:20,005 - matplotlib.font_manager - DEBUG - Using fontManager instance from C:\Users\USER\.matplotlib\fontlist-v390.json
2025-08-29 22:32:20,200 - root - INFO - Módulo gui.app importado correctamente
2025-08-29 22:32:20,201 - root - INFO - Configuración de CustomTkinter establecida
2025-08-29 22:32:20,326 - root - INFO - Ventana principal creada
2025-08-29 22:32:21,359 - gui.simulation_panel - INFO - UI del panel de simulación configurada correctamente
2025-08-29 22:32:21,652 - root - INFO - GenealogyApp inicializada correctamente
2025-08-29 22:32:21,653 - root - INFO - Iniciando bucle principal de la aplicación...
2025-08-29 22:34:06,290 - matplotlib - DEBUG - matplotlib data path: C:\Users\USER\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\matplotlib\mpl-data
2025-08-29 22:34:06,313 - matplotlib - DEBUG - CONFIGDIR=C:\Users\USER\.matplotlib
2025-08-29 22:34:06,316 - matplotlib - DEBUG - interactive is False
2025-08-29 22:34:06,316 - matplotlib - DEBUG - platform is win32
2025-08-29 22:34:06,339 - root - INFO - Matplotlib backend configurado correctamente
2025-08-29 22:34:06,409 - root - INFO - CustomTkinter importado correctamente
2025-08-29 22:34:06,798 - matplotlib - DEBUG - CACHEDIR=C:\Users\USER\.matplotlib
2025-08-29 22:34:06,800 - matplotlib.font_manager - DEBUG - Using fontManager instance from C:\Users\USER\.matplotlib\fontlist-v390.json
2025-08-29 22:34:07,206 - root - INFO - Módulo gui.app importado correctamente
2025-08-29 22:34:07,207 - root - INFO - Configuración de CustomTkinter establecida
2025-08-29 22:34:07,316 - root - INFO - Ventana principal creada
2025-08-29 22:34:08,121 - gui.simulation_panel - INFO - UI del panel de simulación configurada correctamente
2025-08-29 22:34:08,278 - root - INFO - GenealogyApp inicializada correctamente
2025-08-29 22:34:08,279 - root - INFO - Iniciando bucle principal de la aplicación...
